*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/VOMS-delRole b/org.glite.testsuites.ctb/VOMS/VOMS-delRole
--- a/org.glite.testsuites.ctb/VOMS/VOMS-delRole
+++ b/org.glite.testsuites.ctb/VOMS/VOMS-delRole
@@ -17,18 +17,12 @@
 # provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
-
+export voms_host=$1
 source $SAME_SENSOR_HOME/tests/config_file
-
-voms_host=$1
-voms_tmp=/tmp/$voms_host"_tmp"
-voms_stderr=/tmp/$voms_host"_stderr"
-tempo=/tmp/$voms_host"_string"
-
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-rm -rf $tempo
+#rm -rf $tempo
 
 
 echo ""
@@ -67,14 +61,17 @@ voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
 grep "$ROLE" $voms_tmp > /dev/null
 
 
-if [ $? == 1 ]; then
-   echo "Test is OK"
-   exit $SAME_OK
+if [ $? == 0 ]; then
+   echo "Role not deleted, LIST:<<"
+   cat $voms_tmp
+   echo ">>,     Test has failed"
+   exit $SAME_ERROR
 fi
 
-echo "Role not deleted, LIST:<<"
-cat $voms_tmp
-echo ">>,     Test has failed"
-exit $SAME_ERROR
+rm -rf $voms_tmp
+rm -rf $voms_stderr
+
+echo "Test is OK"
+exit $SAME_OK
 
 
