bug #86490

diff --git a/org.glite.wmproxy/src/scripts/glite-wms-wmproxy-purge-proxycache.in b/org.glite.wmproxy/src/scripts/glite-wms-wmproxy-purge-proxycache.in
--- a/org.glite.wmproxy/src/scripts/glite-wms-wmproxy-purge-proxycache.in
+++ b/org.glite.wmproxy/src/scripts/glite-wms-wmproxy-purge-proxycache.in
@@ -25,36 +25,42 @@ valid_proxies=0
 removed_proxies=0
 not_removed_proxies=0
 while read i; do
-  log "processing file: $i"
-  rmdir $i 2>/dev/null
-  if [ $? -eq 0 ]; then
-    log "removed empty directory: $i"
-    continue
-  fi
-  $openssl_command x509 -in $i -noout 2>/dev/null
-  if [ $? -eq 0 ]; then
-    expiry_date=`$openssl_command x509 -in $i -noout -enddate 2>/dev/null`
-    if [ -z "$expiry_date" ]; then
-      log "   couldn't remove (unable to get the proxy time left)"
+  log "processing file/directory: $i"
+  if [ -d "$i" ]; then
+    rmdir $i 2>/dev/null
+    if [ $? -eq 0 ]; then
+      log "removed empty directory: $i"
+      continue
     fi
-    not_after=`echo $expiry_date|cut -d '=' -f 2`
-    not_after_epoch=`date +%s -d "$not_after"`
-    now_epoch=`date +%s`
-    if [ $now_epoch -gt $not_after_epoch ]; then
-      log "   expired proxy: removing proxy file..."
-      rm -f $i
-      rmdir `dirname $i`
-      if [ $? != 0 ]; then
-        log "   ...couldn't remove proxy file"
-        not_removed_proxies=`expr $not_removed_proxies + 1`
-      else
-        log "   ...proxy file has been removed"
-        removed_proxies=`expr $removed_proxies + 1`
+  else
+    $openssl_command x509 -in $i -noout 2>/dev/null
+    if [ $? -eq 0 ]; then
+      expiry_date=`$openssl_command x509 -in $i -noout -enddate 2>/dev/null`
+      if [ -z "$expiry_date" ]; then
+        log "   couldn't remove (unable to get the proxy time left)"
       fi
-    else
-      time_left=`expr $not_after_epoch - $now_epoch`
-      log "   the proxy is still valid ($time_left seconds left)"
-      valid_proxies=`expr $valid_proxies + 1`
+      not_after=`echo $expiry_date|cut -d '=' -f 2`
+      not_after_epoch=`date +%s -d "$not_after"`
+      now_epoch=`date +%s`
+      if [ $now_epoch -gt $not_after_epoch ]; then
+        log "   expired proxy: removing proxy file..."
+        if [ -f "`dirname $i`/userkey.pem" ]; then
+          rm -f `dirname $i`/userkey.pem
+        fi
+        rm -f $i
+        rmdir `dirname $i`
+        if [ $? != 0 ]; then
+          log "   ...couldn't remove proxy file or there are other files in the parent directory"
+          not_removed_proxies=`expr $not_removed_proxies + 1`
+        else
+          log "   ...proxy file has been removed"
+          removed_proxies=`expr $removed_proxies + 1`
+        fi
+      else
+        time_left=`expr $not_after_epoch - $now_epoch`
+        log "   the proxy is still valid ($time_left seconds left)"
+        valid_proxies=`expr $valid_proxies + 1`
+      fi
     fi
   fi
 done < $tmp_file
