*** empty log message ***

diff --git a/org.glite.testsuites.ctb/LFC/tests/LFC-CLI-rmfile b/org.glite.testsuites.ctb/LFC/tests/LFC-CLI-rmfile
--- a/org.glite.testsuites.ctb/LFC/tests/LFC-CLI-rmfile
+++ b/org.glite.testsuites.ctb/LFC/tests/LFC-CLI-rmfile
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Date: 09/11/2007                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Rename  LFC subdirectories for VO                                #
+# Description of the test: Delete  LFC subdirectories for VO                                #
 #                                                                                           #
 # Input Parameters:                                                                         #
 #       - VO name                                                                           #
@@ -25,7 +25,6 @@ function clear (){
 }
 
 source $SAME_SENSOR_HOME/tests/config_file
-
 echo $SAME_OK
 echo $SAME_VO
 
@@ -34,102 +33,92 @@ rm -rf $lfc_stderr
 
 date
 echo "<br>"
-echo "Test LFC CLI rename diectory. lfc-rename <olddirname> <newdirname>"
+echo "Test LFC CLI remove diectory. lfc-rm -r <dirname>"
 echo "<br>"
 echo "VO=$vo_name"
 echo "<br>"
 echo "<br>"
 
 
-main_dir="$LFCDIR/renamedir"
+main_dir="$LFCDIR/rmfile"
 
 echo "Scenario: Direcrory exists"
 echo "1. Create main directory: $main_dir"
 echo "<br>"
 lfc-mkdir -p $main_dir
 
-
-rdname="rdonly"
-rdon="$main_dir/$rdname"
-newDn="newDname"
-newDname="$main_dir/$newDn"
-
-echo "2. Rename 'read only' directory"
-echo "This requires write permission in the parent directories, not current"
-
+rdon="$main_dir/rdonly"
+echo "2. Remove 'read only' directory"
 lfc-mkdir -m 400 $rdon
-lfc-rename $rdon $newDname 2> $lfc_stderr
-cat $lfc_stderr
+lfc-rm -f -r $rdon 2> $lfc_stderr
 grep "Permission denied" $lfc_stderr > /dev/null
-if [ $? == 1 ]; then	# non correct
-#if [ $? == 0 ]; then	# correct 
-   echo "Non correct lfc-rename result, Test try rename read-only directory"
-   echo " and with write permission for parent directory, lfc-rename MUST rename this directory!!!"
-   echo "Parent directory is $main_dir:"
-   lfc-ls -l "/grid/$vo_name/$LFC_HOST"
+
+if [ $? == 1 ]; then 
+   echo "Non correct lfc-rm result"
    echo "Test is failed"
    lfc-chmod 777 $rdon
    clear $main_dir
    exit $SAME_ERROR
 fi
+lfc-chmod 777 $rdon
+clear $rdon
 echo "OK"
 
 echo
-echo "2. Rename ordinary directory"
-lfc-chmod 777 $rdon
-lfc-rename $rdon $newDname
-lfc-ls $main_dir > $lfc_tmp
+echo "3.  Create $DMAX subdirectories"
+echo "<br>"
+counter=0
+dir=$main_dir
+pdir=$main_dir
 
-grep $newDn $lfc_tmp  > /dev/null
+while [ $counter -lt $DMAX ]; do
+  subdir="subdir-$counter"
+  dir=$dir/$subdir
+  echo "new dir:$dir"
+  lfc-mkdir $dir
+  lfc-ls $pdir > $lfc_tmp
+  grep $subdir $lfc_tmp > /dev/null
+  
+  if [ $? == 1 ]; then 
+    echo "Test is failed"
+    clear $main_dir
+    exit $SAME_ERROR
+  fi
+  
+  pdir=$dir
+  let counter=counter+1
+done
 
+echo "4. Remove all subdirectories, use -R option"
+lfc-rm -R  -f $main_dir  
+echo "5. Check deletion result"
+
+lfc-ls $main_dir 2> $lfc_stderr
+grep "No such file or directory" $lfc_stderr > /dev/null
+ 
 if [ $? == 1 ]; then 
-   echo "Non correct lfc-rename result"
-   echo "Test is failed"
-   clear $main_dir
-   exit $SAME_ERROR
-fi
-
-#clear $newDname
+    echo "Test is failed"
+    clear $main_dir
+    exit $SAME_ERROR
+fi 
 echo "OK"
 
-echo "2. Rename by using LFC_HOME"
-
-export LFC_HOME=$main_dir
-#lfc-ls $main_dir
-newdir="newdirname"
-lfc-rename $newDn $newdir
-lfc-ls $main_dir > $lfc_tmp
-#cat $lfc_tmp 
-grep $newdir $lfc_tmp  > /dev/null
-
-if [ $? == 1 ]; then 
-   echo "Non correct lfc-rename result"
-   echo "Test is failed"
-   clear $main_dir
-   exit $SAME_ERROR
-fi
-clear $main_dir
-echo "OK"
-
-
-echo "3. SCENARIO: Rename nonexisting directory: $rdon"
+echo "2. SCENARIO: Delete nonexisting directory: $main_dir"
 echo "<br>"
 
-lfc-rename $rdon $newDname   2> $lfc_stderr
-#cat $lfc_stderr
+lfc-rm -r -f $main_dir  2> $lfc_stderr
+cat $lfc_stderr
 grep "No such file or directory" $lfc_stderr > /dev/null
 
-if [ $? == 1 ]; then 
+if [ $? == 0 ]; then 
    echo "Noncorrect diagnose, exit"
    cat $lfc_stderr
    echo "Test is failed"
    clear $main_dir
    exit $SAME_ERROR
 fi
+
 echo "OK"
-
-
-
 
 echo
 echo "Cleaning tasks"
