Test fixes for 2063 and 2390

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
@@ -1,24 +1,26 @@
 #!/bin/bash
 # Date: 01/12/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Test ACL  create entry  command (add--acl-entry) for Role        #
+# Description of the test: Test ACL  create entry  command (add-ACL-entry) for role         #
 #                                                                                           #
 # Input Parameters:                                                                         #
-#       - VO name                                                                           #                                    
+#       - VO name                                                                           # 
 #       - VO host name                                                                      #
 #       - groupname                                                                         #
+#       - rolename                                                                          #
 #       - fake user certificate file path                                                   #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
 #       - 1 configured VO which is empty                                                    #
 #                                                                                           #
-#                                                                                           #                                                               
+#                                                                                           #
 #############################################################################################
 #                                                                                           #
 #                                                                                           #
 #############################################################################################
-echo "<pre>"
+
 export voms_host=$1
+echo "<pre>"
 source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
@@ -27,24 +29,29 @@ rm -rf $tempo
 
 date
 echo "<br>"
-echo "Test VOMS-crACLRole:"
+echo "Test VOMS-crACLGroup:"
 echo "<br>"
 echo "VO=$vo_name"
 echo "<br>"
-echo "Role=$ROLE"
+echo "group=$GROUP"
+echo "<br>"
+echo "role=$ROLE"
 echo "<br>"
 echo "fake user=$USER"
 echo "<br>"
 
-oper=( all create delete add remove set-acl get-acl set-default-acl get-default-acl list )
+ACE_RIGHTS=( CONTAINER_READ MEMBERSHIP_READ ACL_READ REQUESTS_READ ATTRIBUTES_READ CONTAINER_WRITE MEMBERSHIP_WRITE ACL_WRITE REQUESTS_WRITE ATTRIBUTES_WRITE ACL_DEFAULT ALL )
 
-echo "SCENARIO: empty VO"
+USER_SUBJECT=$(openssl x509 -in $USER -noout -subject | sed -e 's/^subject=[ ]*//')
+USER_ISSUER=$(openssl x509 -in $USER -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+echo "<br>SCENARIO: empty VO"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr
+voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/Role=$ROLE" $USER ALL FALSE > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchRoleException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Error creating the role"
+    echo "Setting ACE on non-existing role did not generate an error."
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -53,65 +60,111 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create Role <$ROLE> and add 10 ACL entries"
+echo "SCENARIO: Create group <$GROUP>, role <$ROLE> and try to set each right"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-for ind in 0 1 2 3 4 5 6 7 8 9
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host create-role "$ROLE"
+
+for ind in 0 1 2 3 4 5 6 7 8 9 10 11
 do
- OP=${oper[ind]}
- echo "Create ACL entry $OP for user for Role $ROLE"
- voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
-done
-voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
+ OP=${ACE_RIGHTS[ind]}
 
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-grep "$user_subject" $voms_tmp > $tempo
+ echo "<br>Create ACL entry with right $OP for user $USER_SUBJECT and context /$vo_name/$GROUP/Role=$ROLE"
+ voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" $USER $OP FALSE
 
-echo "Check added ACL entries"
-echo "<br>"
-ops=`cat $tempo | cut -d"|" -f3`
-echo $ops > $tempo
-for ind in 0 1 2 3 4 5 6 7 8 9
-do
- OP=${oper[ind]}
- grep $OP $tempo > /dev/null
+ echo -n "<br>Check whether the right is properly set..."
+ voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=$ROLE" > $voms_tmp
 
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Error creating the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
+ SET_PERM_LIST=$(grep "^($USER_SUBJECT,$USER_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+ if [ "$SET_PERM_LIST" != "$OP" ]; then
+    voms-admin --vo=$vo_name --host delete-group "/$vo_name/$GROUP"
+    voms-admin --vo=$vo_name --host delete-role "$ROLE"
+    echo "FAILED"
+    echo "<br>Error in creating an ACE with right $OP"
+    echo "<br>Test has failed"
     echo "<br>"
     exit $SAME_ERROR
  fi
- 
+ echo "OK"
 done
 
-echo "SCENARIO: Add existing ACL entry in role $ROLE"
+echo "<br>SCENARIO: Check ACE with multiple rights set"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "list" $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null
+
+for ind in 1 2 3 4 5 6 7 8 9 10
+do
+ IFS=,
+ OP="${ACE_RIGHTS[*]:0:$ind}"
+
+ echo "<br>Create ACL entry with rights $OP for user $USER_SUBJECT and context /$vo_name/$GROUP/Role=$ROLE"
+ voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" $USER "$OP" FALSE
+
+ echo -n "<br>Check whether the rights are properly set..."
+ voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=$ROLE" > $voms_tmp
+
+ SET_PERM_LIST="$(grep "^($USER_SUBJECT,$USER_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")"
+
+ for CURRENT_PERM in $SET_PERM_LIST; do
+    j=0
+    FOUND="no"
+
+    while [ $j -lt $ind ]; do
+       if [ "${ACE_RIGHTS[$j]}" = "$CURRENT_PERM" ]; then
+          FOUND="yes"
+          break
+       fi
+       j=$[$j+1]
+    done
+
+    if [ "$FOUND" = "no" ]; then
+       voms-admin --vo=$vo_name --host delete-group "/$vo_name/$GROUP"
+       voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+       echo "FAILED"
+       echo "<br>Permission $CURRENT_PERM should not be set but it is."
+       echo "<br>Error in add-ACL-entry or get-ACL when using multiple permissions."
+       echo "<br>Test has failed."
+       echo "<br>"
+       exit $SAME_ERROR
+    fi
+
+  j=0
+  while [ $j -lt $ind ]; do
+
+     FOUND="no"
+     for CURRENT_PERM in $SET_PERM_LIST; do
+        if [ "${ACE_RIGHTS[$j]}" = "$CURRENT_PERM" ]; then
+           FOUND="yes"
+           break
+        fi
+     done
+
+     if [ "$FOUND" = "no" ]; then
+        voms-admin --vo=$vo_name --host delete-group "/$vo_name/$GROUP"
+        voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+        echo "FAILED"
+        echo "<br>Permission ${ACE_RIGHTS[$j]} should be set but it is not."
+        echo "<br>Error in add-ACL-entry or get-ACL when using multiple permissions."
+        echo "<br>Test has failed."
+        echo "<br>"
+        exit $SAME_ERROR
+     fi
+  
+     j=$[$j+1]
+  done
+ done
+
+ echo "OK"
+done
+
+echo "<BR>SCENARIO: Try to create an ACL entry for an unknown operation"
+echo "<br>"
+
+voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" $USER "lllist" FALSE 2> $voms_stderr
+grep "ValueError: lllist is not a supported VOMSPermission" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Incorrect error message"
-    echo "<br>"
-    cat $voms_stderr
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
-
-echo "SCENARIO: Try to create an ACL entry for an unknown operation"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "lllist" $USER 2> $voms_stderr
-grep "Unknown operation:" $voms_stderr > /dev/null
-
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+    voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
     echo "Incorrect error message"
     echo "<br>"
     cat $voms_stderr
@@ -124,7 +177,9 @@ fi
 echo "Cleaning tasks"
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listACLRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listACLRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listACLRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listACLRole
@@ -1,22 +1,24 @@
 #!/bin/bash
 # Date: 01/12/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Test ACL  list command (get-acl)                                 #
+# Description of the test: Test ACL list command (get-ACL) for role-based context           #
 #                                                                                           #
 # Input Parameters:                                                                         #
-#       - VO name                                                                           #                                    
+#       - VO name                                                                           #    
 #       - VO host name                                                                      #
-#       - Role                                                                              #
+#       - groupname                                                                         #
+#       - rolename                                                                          #
 #       - fake user certificate file path                                                   #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
 #       - 1 configured VO which is empty                                                    #
 #                                                                                           #
-#                                                                                           #                                                               
+#                                                                                           #    
 #############################################################################################
 #                                                                                           #
 #                                                                                           #
 #############################################################################################
+
 echo "<pre>"
 export voms_host=$1
 source $SAME_SENSOR_HOME/tests/config_file
@@ -33,21 +35,31 @@ echo "VO=$vo_name"
 echo "<br>"
 echo "group=$GROUP"
 echo "<br>"
-echo "Role=$ROLE"
+echo "role=$ROLE"
+echo "<br>"
+echo "fake user=$USER"
 echo "<br>"
 
-op1="list"
-op2="create"
-op3="delete"
-allow="allow"
+USER1_SUBJECT=$(openssl x509 -in $USER1 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER1_ISSUER=$(openssl x509 -in $USER1 -noout -issuer | sed -e 's/^issuer=[ ]*//')
 
-echo "SCENARIO: empty VO"
+USER2_SUBJECT=$(openssl x509 -in $USER2 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER2_ISSUER=$(openssl x509 -in $USER2 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER3_SUBJECT=$(openssl x509 -in $USER3 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER3_ISSUER=$(openssl x509 -in $USER3 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER4_SUBJECT=$(openssl x509 -in $USER4 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER4_ISSUER=$(openssl x509 -in $USER4 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+echo "SCENARIO: list ACL for a non-existent group (empty VO)"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null
+
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/Role=$ROLE" > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchRoleException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message"
+    echo "Unexpected message while listing the ACL for a non-existent role"
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -56,68 +68,77 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create role <$ROLE> and add 3 ACL entries"
+echo "SCENARIO: Create group <$GROUP>, role <$ROLE> and add 3 ACL entries (for USER1, USER3, USER4 - see the configuration file)."
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $allow $op1 $USER
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $allow $op2 $USER
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $allow $op3 $USER
-voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
 
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-grep "$user_subject" $voms_tmp > $tempo
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host create-role "$ROLE"
+
+voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" $USER1 "CONTAINER_READ,CONTAINER_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" $USER3 "ATTRIBUTES_READ,ATTRIBUTES_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" "$USER4_SUBJECT" "$USER4_ISSUER" "ACL_READ,ACL_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" "$USER4_SUBJECT" "$USER4_ISSUER" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/Role=$ROLE" "$USER4_SUBJECT" "$USER4_ISSUER" "REQUESTS_READ,ACL_DEFAULT" FALSE
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=$ROLE" > $voms_tmp
+
+SET_PERM_LIST1=$(grep "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST2=$(grep "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST3=$(grep "^($USER4_SUBJECT,$USER4_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+
 echo "Check added ACL entries"
 echo "<br>"
-ops=`cat $tempo | cut -d"|" -f3`
-echo $ops > $tempo
 
-grep "$op1" $tempo > /dev/null
+if ! (echo $SET_PERM_LIST1 | grep CONTAINER_READ | grep -q CONTAINER_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+   echo "Error listing the ACE for $USER1_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
+if ! (echo $SET_PERM_LIST2 | grep ATTRIBUTES_READ | grep -q ATTRIBUTES_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+   echo "Error listing the ACE for $USER3_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
-grep "$op2" $tempo > /dev/null
+if ! (echo $SET_PERM_LIST3 | grep REQUESTS_READ | grep -q ACL_DEFAULT); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+   echo "Error listing the ACE for $USER4_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
-
-grep "$op3" $tempo > /dev/null
-
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
+if ((echo $SET_PERM_LIST3 | grep -q ACL_READ) || (echo $SET_PERM_LIST3 | grep -q ACL_WRITE)); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+   echo "Error listing the ACE for $USER4_SUBJECT; unexpected right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
 echo "Cleaning tasks"
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+voms-admin --vo=$vo_name --host $voms_host delete-role "$ROLE"
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
 echo "Test OK"
-echo "</pre>"
+echo "<pre>"
 exit $SAME_OK
+
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Date: 01/12/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Test list default ACL entrys for group(get-default-acl)          #
+# Description of the test: Test default ACL list command (get-default-ACL)                  #
 #                                                                                           #
 # Input Parameters:                                                                         #
 #       - VO name                                                                           #                                    
@@ -36,18 +36,64 @@ echo "<br>"
 echo "fake user=$USER"
 echo "<br>"
 
-op1="list"
-op2="create"
-op3="delete"
-allow="allow"
+USER1_SUBJECT=$(openssl x509 -in $USER1 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER1_ISSUER=$(openssl x509 -in $USER1 -noout -issuer | sed -e 's/^issuer=[ ]*//')
 
-echo "SCENARIO: empty VO"
+USER2_SUBJECT=$(openssl x509 -in $USER2 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER2_ISSUER=$(openssl x509 -in $USER2 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER3_SUBJECT=$(openssl x509 -in $USER3 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER3_ISSUER=$(openssl x509 -in $USER3 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER4_SUBJECT=$(openssl x509 -in $USER4 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER4_ISSUER=$(openssl x509 -in $USER4 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+# Discover the subject of the user running the tests using the proxy
+EXEC_USER_SUBJECT=$(voms-proxy-info -identity -dont-verify-ac)
+if [ $? == 1 ]; then
+    echo "Cannot discover the subject of the user running the test. voms-proxy-info returned an error.Skipping the test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+# Discover the issuer for this user (this user should be granted ALL rights for the top group)
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name > $voms_tmp
+if [ $? == 1 ]; then
+    echo "Cannot fetch ACL for top group. Skipping test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+EXEC_USER_ISSUER=$(grep "$EXEC_USER_SUBJECT" $voms_tmp | head -1 | cut -f 2 -d ',' | cut -f 1 -d ')')
+if [ -z "$EXEC_USER_ISSUER" ]; then
+    echo "Cannot find the CA subject. Skipping the test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "Starting the test..."
+echo "Executed by: $EXEC_USER_SUBJECT, $EXEC_USER_ISSUER"
+
+echo "SCENARIO: list default ACL for a non-existent group (empty VO)"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
+
+voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchGroupException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message"
+    echo "Unexpected message while listing the ACL for a non-existent group"
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -56,68 +102,153 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create group <$GROUP> and add 3 default ACL entries"
+echo "SCENARIO: Create group <$GROUP> and add ACL entries in the default ACL."
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
-voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op1 $USER
-voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op2 $USER
-voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op3 $USER
-voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp
 
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-grep "$user_subject" $voms_tmp > $tempo
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP
+voms-admin --vo=$vo_name --host $voms_host add-default-ACL-entry "/"$vo_name"/"$GROUP $USER1 "CONTAINER_READ,CONTAINER_WRITE" 
+voms-admin --vo=$vo_name --host $voms_host add-default-ACL-entry "/"$vo_name"/"$GROUP $USER3 "ATTRIBUTES_READ,ATTRIBUTES_WRITE" 
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "$USER4_SUBJECT" "$USER4_ISSUER" "ACL_READ,ACL_WRITE" 
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-default-ACL-entry "/"$vo_name"/"$GROUP "$USER4_SUBJECT" "$USER4_ISSUER" 
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "$USER4_SUBJECT" "$USER4_ISSUER" "REQUESTS_READ,ACL_DEFAULT" 
+
+echo "<br>Add ACE (ALL rights) in the default ACL for the user executing the test"
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "$EXEC_USER_SUBJECT" "$EXEC_USER_ISSUER" ALL
+
+echo "<br>Create a subgroup and inspect its ACL"
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+
+echo "Check the automatically created ACL entries in the child"
+echo "<br>"
+
+echo "Inspect the contents of the default ACL"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP"/"subgroup_acl_test > $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Unexpected error at get-ACL for the ancestor. Unable to obtain the list"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+SET_PERM_LIST1=$(grep "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST2=$(grep "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST3=$(grep "^($USER4_SUBJECT,$USER4_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+
+if ! (echo $SET_PERM_LIST1 | grep CONTAINER_READ | grep -q CONTAINER_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER1_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+if ! (echo $SET_PERM_LIST2 | grep ATTRIBUTES_READ | grep -q ATTRIBUTES_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER3_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+if ! (echo $SET_PERM_LIST3 | grep REQUESTS_READ | grep -q ACL_DEFAULT); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER4_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+if ((echo $SET_PERM_LIST3 | grep -q ACL_READ) || (echo $SET_PERM_LIST3 | grep -q ACL_WRITE)); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER4_SUBJECT; unexpected right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+echo "Inspect the contents of the default ACL"
+voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Unexpected error at get-default-ACL. Unable to obtain the list"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+SET_PERM_LIST1=$(grep "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST2=$(grep "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+SET_PERM_LIST3=$(grep "^($USER4_SUBJECT,$USER4_ISSUER): " $voms_tmp | sed -e "s/^([^\)]*): //")
+
 echo "Check added ACL entries"
 echo "<br>"
-ops=`cat $tempo | cut -d"|" -f3`
-echo $ops > $tempo
 
-grep "$op1" $tempo > /dev/null
+if ! (echo $SET_PERM_LIST1 | grep CONTAINER_READ | grep -q CONTAINER_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER1_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
+if ! (echo $SET_PERM_LIST2 | grep ATTRIBUTES_READ | grep -q ATTRIBUTES_WRITE); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER3_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
-grep "$op2" $tempo > /dev/null
+if ! (echo $SET_PERM_LIST3 | grep REQUESTS_READ | grep -q ACL_DEFAULT); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER4_SUBJECT; missing right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
-
-grep "$op3" $tempo > /dev/null
-
- if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error listing the ACL"
-    echo "<br>"
-    cat $tempo
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
+if ((echo $SET_PERM_LIST3 | grep -q ACL_READ) || (echo $SET_PERM_LIST3 | grep -q ACL_WRITE)); then
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+   voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error listing the ACE for $USER4_SUBJECT; unexpected right"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
 
 echo "Cleaning tasks"
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"subgroup_acl_test
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
 echo "Test OK"
-echo "</pre>"
+echo "<pre>"
 exit $SAME_OK
+
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-RoleOrder b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-RoleOrder
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-RoleOrder
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-RoleOrder
@@ -63,7 +63,7 @@ done
 }
 function clearTask {
     echo "Delete user"
-    voms-admin --vo=$vo_name --host $voms_host delete-user "$USER_SUBJECT" "$USER_ISSUER" 
+    voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER" 
     echo "Delete all groups"
     delGroups
     echo "Delete all roles"
@@ -89,7 +89,6 @@ USER_SUBJECT=$(openssl x509 -in $USERCERT -noout -subject | sed -e 's/^subject=[
 USER_ISSUER=$(openssl x509 -in $USERCERT -noout -issuer | sed -e 's/^issuer=[ ]*//')
 
 echo "1. Create new user and proxy"
-#voms-admin --vo=$vo_name --host $voms_host delete-user "$USER_SUBJECT" "$USER_ISSUER" 
 voms-admin --vo=$vo_name --host $voms_host create-user $USER
 echo "Extract by openssl from usercert.pem"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
@@ -119,13 +118,14 @@ for group in ${Groups[*]}
 do
     groupi="/$vo_name/$group"
     #echo "Add member to group: $groupi"
-    voms-admin --vo=$vo_name --host $voms_host add-member $groupi "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert add-member $groupi "$USER_SUBJECT" "$USER_ISSUER"
 done
 
-
+# TO CHECK[B
+#
 #echo "1.3.1. List user groups:"
 #voms-admin --vo=$vo_name --host $voms_host list-user-groups "$USER_SUBJECT" "$USER_ISSUER" 
-
+#
 #echo "1.3.2. Check members for each group - list members"
 #for group in ${Groups[*]}
 #do
@@ -133,24 +133,24 @@ done
 #    echo "Members in  group: $groupi"
 #    voms-admin --vo=$vo_name --host $voms_host list-members $groupi
 #done
-
+#
 
 echo "1.4. Assign Roles to users in group /$vo_name ($ROLEA, $ROLEB) and in 5 groups"
-    voms-admin --vo=$vo_name --host $voms_host assign-role /$vo_name "$ROLEA" "$USER_SUBJECT" "$USER_ISSUER"
-    voms-admin --vo=$vo_name --host $voms_host assign-role /$vo_name "$ROLEB" "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert assign-role /$vo_name "$ROLEA" "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert assign-role /$vo_name "$ROLEB" "$USER_SUBJECT" "$USER_ISSUER"
 
 co=0
 for group in ${Groups[*]}
 do
     role=${Roles[co]}
     groupi="/$vo_name/$group"
-    #echo "Assign role=$role in  group $groupi to user"
-    voms-admin --vo=$vo_name --host $voms_host assign-role $groupi $role "$USER_SUBJECT" "$USER_ISSUER"
+    echo "Assign role=$role in  group $groupi to user"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert assign-role $groupi $role "$USER_SUBJECT" "$USER_ISSUER"
     let co=co+1
 done
 
 echo "1.4.1. List user roles:"
-voms-admin --vo=$vo_name --host $voms_host  list-user-roles "$USER_SUBJECT" "$USER_ISSUER"
+voms-admin --vo=$vo_name --host $voms_host --nousercert list-user-roles "$USER_SUBJECT" "$USER_ISSUER"
 
 echo
 echo "2. Destroy and create proxy with 1 Role=$ROLEA"
@@ -232,7 +232,7 @@ fi
 echo "Test DN is OK"
 
 
-echo "4. Check result -fqan"
+echo "3.3. Check result -fqan"
 voms-proxy-info -fqan > $voms_tmp
 cat $voms_tmp
 
@@ -243,6 +243,82 @@ num=`grep -n "$patt1" $voms_tmp | cut -d":" -f1`
 echo "Nline=$num"
 
 if [ $num != 1 ]; then
+    echo "Test has failed"
+    clearTask
+    exit $SAME_FAILED
+fi
+echo "OK"
+
+echo
+echo "4. Destroy and create proxy with 2 Roles: $ROLEA, $ROLEB and check the -voms inferred order"
+echo "Command:"
+echo "  voms-proxy-init -voms $vo_name:/$vo_name/Role=$ROLEB -voms $vo_name -voms $vo_name:/$vo_name/Role=$ROLEA"
+echo "                  -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS"
+
+voms-proxy-destroy
+voms-proxy-init -voms "$vo_name:/$vo_name/Role=$ROLEB" -voms $vo_name -voms "$vo_name:/$vo_name/Role=$ROLEA" -vomses $VOMSES  -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+
+echo "4.1. Check exit code and subject name"
+if [ $? == 1 ]; then
+        echo "Test has failed"
+        clearTask
+        exit $SAME_ERROR
+fi
+echo "Exit code - OK"
+
+
+voms-proxy-info -all > $voms_tmp
+cat $voms_tmp
+
+echo "4.2. Check user DN"
+grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    clearTask
+    exit $SAME_ERROR
+fi
+echo "Test DN is OK"
+
+
+echo "4.3. Check result -fqan"
+voms-proxy-info -fqan > $voms_tmp
+cat $voms_tmp
+
+patt1="/$vo_name/Role=$ROLEB/Capability=NULL"
+patt2="/$vo_name/Role=NULL/Capability=NULL"
+patt3="/$vo_name/Role=$ROLEA/Capability=NULL"
+
+echo "Check 1 order (expected 1 line: '$patt1'):"
+
+num=`grep -n "$patt1" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 1 ]; then
+    echo "Test has failed"
+    clearTask
+    exit $SAME_FAILED
+fi
+echo "OK"
+
+echo "Check 2 order (expected 1 line: '$patt2'):"
+
+num=`grep -n "$patt2" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 2 ]; then
+    echo "Test has failed"
+    clearTask
+    exit $SAME_FAILED
+fi
+echo "OK"
+
+echo "Check 3 order (expected 1 line: '$patt3'):"
+
+num=`grep -n "$patt3" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 3 ]; then
     echo "Test has failed"
     clearTask
     exit $SAME_FAILED
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-order b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-order
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-order
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-order
@@ -78,7 +78,7 @@ done
 }
 
 function clearTask {
-    voms-admin --vo=$vo_name --host $voms_host delete-user "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER"
     delSubgroups
     delGroups
 }
@@ -130,7 +130,7 @@ for group in ${Groups[*]}
 do
     groupi="/$vo_name/$group"
     echo "Add member to group: $groupi"
-    voms-admin --vo=$vo_name --host $voms_host add-member $groupi "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert add-member $groupi "$USER_SUBJECT" "$USER_ISSUER"
 done
 
 echo "1.4. Add user to subgroups as group member"
@@ -140,12 +140,12 @@ for group in ${Subgroups[*]}
 do 
     groupi="$work/$group"
     echo "Add member to sub-group: $groupi"
-    voms-admin --vo=$vo_name --host $voms_host add-member "$groupi" "$USER_SUBJECT" "$USER_ISSUER"
+    voms-admin --vo=$vo_name --host $voms_host --nousercert add-member "$groupi" "$USER_SUBJECT" "$USER_ISSUER"
     work="$groupi"    
 done
 
 echo "1.5. List user groups:"
-voms-admin --vo=$vo_name --host $voms_host list-user-groups "$USER_SUBJECT" "$USER_ISSUER"
+voms-admin --vo=$vo_name --host $voms_host --nousercert list-user-groups "$USER_SUBJECT" "$USER_ISSUER"
 
 echo "2. Check proxy info"
 echo "Destroy and Create proxy"
@@ -216,6 +216,74 @@ echo "OK"
 echo "Check 3 order (expected 3 line: $patt3):"
 #grep -n "$patt3" $voms_tmp
 
+num=`grep -n "$patt3" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 3 ]; then
+   echo "Test has failed"
+   clearTask
+   exit $SAME_FAILED
+fi
+
+echo "Create a new proxy for checking -voms inferred order:"
+echo voms-proxy-init -voms "$vo_name:/$vo_name/group1/sgroup_11" -voms $vo_name -voms "$vo_name:/$vo_name/group1/sgroup_11/sgroup_12/sgroup_13/sgroup_14" -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin
+voms-proxy-init -voms "$vo_name:/$vo_name/group1/sgroup_11" -voms $vo_name -voms "$vo_name:/$vo_name/group1/sgroup_11/sgroup_12/sgroup_13/sgroup_14" -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+
+if [ $? == 1 ]; then
+    echo "Test has failed, exit code=1"
+    clearTask
+    exit $SAME_ERROR
+fi
+echo "exit code - OK"
+
+echo "2.1. Execute voms-proxy-info -all"
+voms-proxy-info -all > $voms_tmp
+
+cat $voms_tmp
+
+echo "2.2. Check user DN"
+grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    clearTask
+    exit $SAME_ERROR
+fi
+
+patt1="/$vo_name/group1/sgroup_11/Role=NULL/Capability=NULL"
+patt2="/$vo_name/group1/Role=NULL/Capability=NULL"
+patt3="/$vo_name/group1/sgroup_11/sgroup_12/sgroup_13/sgroup_14/Role=NULL/Capability=NULL"
+
+echo "Check -fqan"
+voms-proxy-info -fqan > $voms_tmp
+cat $voms_tmp
+
+voms-proxy-destroy
+voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+
+echo "Check 1 order (expected 1 line: $patt1):"
+num=`grep -n "$patt1" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 1 ]; then
+   echo "Test has failed"
+   clearTask
+   exit $SAME_FAILED
+fi
+echo "OK"
+
+echo "Check 2 order (expected 2 line: $patt2):"
+num=`grep -n "$patt2" $voms_tmp | cut -d":" -f1`
+echo "Nline=$num"
+
+if [ $num != 2 ]; then
+   echo "Test has failed"
+   clearTask
+   exit $SAME_FAILED
+fi
+echo "OK"
+
+echo "Check 3 order (expected 3 line: $patt3):"
 num=`grep -n "$patt3" $voms_tmp | cut -d":" -f1`
 echo "Nline=$num"
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLGroup b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLGroup
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLGroup
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLGroup
@@ -36,13 +36,28 @@ echo "<br>"
 echo "fake user=$USER"
 echo "<br>"
 
-echo "SCENARIO: empty VO"
+USER1_SUBJECT=$(openssl x509 -in $USER1 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER1_ISSUER=$(openssl x509 -in $USER1 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER2_SUBJECT=$(openssl x509 -in $USER2 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER2_ISSUER=$(openssl x509 -in $USER2 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER3_SUBJECT=$(openssl x509 -in $USER3 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER3_ISSUER=$(openssl x509 -in $USER3 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER4_SUBJECT=$(openssl x509 -in $USER4 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER4_ISSUER=$(openssl x509 -in $USER4 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+echo "SCENARIO: Try to remove an ACL entry for a non-existent group (empty VO)"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
+
+echo voms-admin --vo=$vo_name --host $voms_host remove-ACL-entry "/"$vo_name"/"$GROUP $USER FALSE
+
+voms-admin --vo=$vo_name --host $voms_host remove-ACL-entry "/"$vo_name"/"$GROUP $USER FALSE > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchGroupException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message"
+    echo "Unexpected behavior when trying to remove an ACL entry for a non-existent group."
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -51,33 +66,26 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create group $GROUP and add ACL entry"
+echo "SCENARIO: Create a group hierarchy /$vo_name/$GROUP/$GROUP, ACL entries and test the removal without propagation"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for group" $voms_stderr > /dev/null
 
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Incorrect error message"
-    echo "<br>"
-    cat $voms_stderr
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP/$GROUP
 
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "/"$vo_name"/"$GROUP $ALLOW $OP $USER
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP "$USER1_SUBJECT" "$USER1_ISSUER" "CONTAINER_READ,CONTAINER_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP/$GROUP "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_READ,ACL_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP "$USER3_SUBJECT" "$USER3_ISSUER" "MEMBERSHIP_READ,MEMBERSHIP_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP/$GROUP "$USER3_SUBJECT" "$USER3_ISSUER" "MEMBERSHIP_READ,MEMBERSHIP_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/"$vo_name"/"$GROUP "$USER1_SUBJECT" "$USER1_ISSUER" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/"$vo_name"/"$GROUP "$USER3_SUBJECT" "$USER3_ISSUER" FALSE
 
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-voms-admin --vo=$vo_name -h $voms_host get-acl "/"$vo_name"/"$GROUP > $voms_tmp
-grep "$user_subject" $voms_tmp > /dev/null
+echo "<BR>Checking ACL for /$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP > $voms_tmp
 
-if [ $? == 0 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error removing the ACL"
+if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Error removing an ACL entry for ($USER1_SUBJECT;/$vo_name/$GROUP)"
     echo "<br>"
     cat $voms_tmp
     echo "<br>"
@@ -86,10 +94,116 @@ if [ $? == 0 ]; then
     exit $SAME_ERROR
 fi
 
-echo "Cleaning tasks"
+if grep -q "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Error removing an ACL entry for ($USER3_SUBJECT;/$vo_name/$GROUP)"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP/$GROUP > $voms_tmp
+
+if ! grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Propagation error. ACL entry for ($USER1_SUBJECT;/$vo_name/$GROUP/$GROUP) is missing but should not."
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+if ! grep -q "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo echo "Propagation error. ACL entry for ($USER3_SUBJECT;/$vo_name/$GROUP/$GROUP) is missing but should not."
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Test the removal of ACL entries with propagation enabled."
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+# Prepare the scenario (restore the ACL entries removed by the previous test for group /$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP "$USER1_SUBJECT" "$USER1_ISSUER" "CONTAINER_READ,CONTAINER_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/"$vo_name"/"$GROUP "$USER3_SUBJECT" "$USER3_ISSUER" "MEMBERSHIP_READ,MEMBERSHIP_WRITE" FALSE
+
+# Do removal with propagation enabled
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/"$vo_name"/"$GROUP "$USER1_SUBJECT" "$USER1_ISSUER" TRUE
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/"$vo_name"/"$GROUP "$USER3_SUBJECT" "$USER3_ISSUER" TRUE
+
+echo "<BR>Checking ACL for /$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP > $voms_tmp
+
+if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Error removing an ACL entry for ($USER1_SUBJECT;/$vo_name/$GROUP) with propagation enabled"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+if grep -q "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Error removing an ACL entry for ($USER3_SUBJECT;/$vo_name/$GROUP) with propagation enabled"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP/$GROUP > $voms_tmp
+
+if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo "Propagation error. ACL entry for ($USER1_SUBJECT;/$vo_name/$GROUP/$GROUP) exists but should not."
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+if grep -q "^($USER3_SUBJECT,$USER3_ISSUER): " $voms_tmp; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    echo echo "Propagation error. ACL entry for ($USER3_SUBJECT;/$vo_name/$GROUP/$GROUP) exists but should not."
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "Cleaning tasks."
+echo "<br>"
+
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
@@ -97,3 +211,4 @@ rm -rf $tempo
 echo "Test OK"
 echo "</pre>"
 exit $SAME_OK
+
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
@@ -1,22 +1,24 @@
 #!/bin/bash
 # Date: 01/12/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Remove ACL entry of Role                                         #
+# Description of the test: Remove ACL entry for a role-based context                        #
 #                                                                                           #
 # Input Parameters:                                                                         #
-#       - VO name                                                                           #                                    
+#       - VO name                                                                           #
 #       - VO host name                                                                      #
-#       - rolename                                                                          #
+#       - groupname                                                                         #
+#       - rolename                                                                          "
 #       - fake user certificate file path                                                   #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
 #       - 1 configured VO which is empty                                                    #
 #                                                                                           #
-#                                                                                           #                                                               
+#                                                                                           #    
 #############################################################################################
 #                                                                                           #
 #                                                                                           #
 #############################################################################################
+
 echo "<pre>"
 export voms_host=$1
 source $SAME_SENSOR_HOME/tests/config_file
@@ -27,22 +29,37 @@ rm -rf $tempo
 
 date
 echo "<br>"
-echo "Test VOMS-removeACLRole:"
+echo "Test VOMS-removeACLGroup:"
 echo "<br>"
 echo "VO=$vo_name"
 echo "<br>"
-echo "Role=$ROLE"
+echo "group=$GROUP"
+echo "<br>"
+echo "role=$ROLE"
 echo "<br>"
 echo "fake user=$USER"
 echo "<br>"
 
-echo "SCENARIO: empty VO"
+USER1_SUBJECT=$(openssl x509 -in $USER1 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER1_ISSUER=$(openssl x509 -in $USER1 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER2_SUBJECT=$(openssl x509 -in $USER2 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER2_ISSUER=$(openssl x509 -in $USER2 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER3_SUBJECT=$(openssl x509 -in $USER3 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER3_ISSUER=$(openssl x509 -in $USER3 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+USER4_SUBJECT=$(openssl x509 -in $USER4 -noout -subject | sed -e 's/^subject=[ ]*//')
+USER4_ISSUER=$(openssl x509 -in $USER4 -noout -issuer | sed -e 's/^issuer=[ ]*//')
+
+echo "SCENARIO: Try to remove an ACL entry for a non-existent role (empty VO)"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null
+
+voms-admin --vo=$vo_name --host $voms_host remove-ACL-entry "/$vo_name/Role=$ROLE" $USER FALSE > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchRoleException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message"
+    echo "Unexpected behavior when trying to remove an ACL entry for a non-existent role."
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -51,45 +68,265 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create role <$ROLE> and add ACL entry"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for role" $voms_stderr > /dev/null
-
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Incorrect error message"
-    echo "<br>"
-    cat $voms_stderr
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
-
-voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
-voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER
-
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
-grep "$user_subject" $voms_tmp > /dev/null
-
- if [ $? == 0 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    echo "Error removing the ACL"
-    echo "<br>"
-    cat $voms_tmp
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
- fi
-
-echo "Cleaning tasks"
+echo "SCENARIO: Create a group hierarchy /$vo_name/$GROUP/$GROUP and two roles (${ROLE}1 and ${ROLE}2), ACL entries and test the removal from role-based context"
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP/$GROUP"
+
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}1"
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}2"
+
+# Add ACL entry for USER1, context is the group and its subgroup. Thus this ACL entries will be set for the two roles too inside the group contexts.
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" "CONTAINER_READ,CONTAINER_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_READ,ACL_WRITE" FALSE
+
+# Now remove the ACL entry for USER1 from the ${ROLE}1 context under /$vo_name/$GROUP with propagation disabled. It should still exists in the ${ROLE}2 contexts under /$vo_name/$GROUP and in both ${ROLE}1 and ${ROLE}2 contexts under /$vo_name/$GROUP/$GROUP.
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/$vo_name/$GROUP/Role=${ROLE}1" "$USER1_SUBJECT" "$USER1_ISSUER" FALSE
+
+# Define a cleanup function
+function doCleanUp {
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP/$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name --host $voms_host delete-role "${ROLE}1"
+    voms-admin --vo=$vo_name --host $voms_host delete-role "${ROLE}2"
+}
+
+# Define a function that inspects the ACL entries for USER1 for the whole hierarchy.
+function checkHierarchy {
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP" > $voms_tmp
+
+   if ! (grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp); then
+       doCleanUp
+       echo "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; The ACE was removed from the group context /$vo_name/$GROUP too. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/Role=${ROLE}1"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=${ROLE}1" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; The ACE was not removed successfully. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/Role=${ROLE}2"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=${ROLE}2" > $voms_tmp
+
+   if ! (grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp); then
+       doCleanUp
+       echo -n "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; "
+       echo "The ACE was also removed from role-based context /$vo_name/$GROUP/Role=${ROLE}2. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP" > $voms_tmp
+
+   if ! (grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp); then
+       doCleanUp
+       echo -n "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; "
+       echo "The ACE was also removed from group-based context /$vo_name/$GROUP/$GROUP. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP/Role=${ROLE}1"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP/Role=${ROLE}1" > $voms_tmp
+
+   if ! (grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp); then
+       doCleanUp
+       echo -n "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; "
+       echo "The ACE was also removed from role-based context /$vo_name/$GROUP/$GROUP/Role=${ROLE}1. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP/Role=${ROLE}2"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP/Role=${ROLE}2" > $voms_tmp
+
+   if ! (grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp); then
+       doCleanUp
+       echo -n "Error while removing an ACL entry from role-based context /$vo_name/$GROUP/Role=${ROLE}1; "
+       echo "The ACE was also removed from role-based context /$vo_name/$GROUP/$GROUP/Role=${ROLE}1. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+}
+
+checkHierarchy
+
+echo "SCENARIO: Create a group hierarchy /$vo_name/$GROUP/$GROUP and two roles (${ROLE}1 and ${ROLE}2), ACL entries and test the removal from role-based context; PROPAGATE is enabled. The result should be the same because the context is role-based."
+echo "<br>"
+
+doCleanUp
+
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP/$GROUP"
+
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}1"
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}2"
+
+# Add ACL entry for USER1, context is the group and its subgroup. Thus this ACL entries will be set for the two roles too inside the group contexts.
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" "CONTAINER_READ,CONTAINER_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_READ,ACL_WRITE" FALSE
+
+# Now remove the ACL entry for USER1 from the ${ROLE}1 context under /$vo_name/$GROUP with propagation enabled. It should still exists in the ${ROLE}2 contexts under /$vo_name/$GROUP and in both ${ROLE}1 and ${ROLE}2 contexts under /$vo_name/$GROUP/$GROUP.
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/$vo_name/$GROUP/Role=${ROLE}1" "$USER1_SUBJECT" "$USER1_ISSUER" TRUE
+
+echo "<BR>Checking ACL for /$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP" > $voms_tmp
+checkHierarchy
+
+echo "<BR>SCENARIO: Check the effect of ACL entry removal for a group on its role contexts."
+
+doCleanUp
+
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
+voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP/$GROUP"
+
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}1"
+voms-admin --vo=$vo_name --host $voms_host create-role "${ROLE}2"
+
+# Add ACL entry for USER1, context is the group and its subgroup with propagation enabled.. Thus this ACL entries will be set for the two roles too inside the group contexts, the subgroup and its two subroles.
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" "CONTAINER_READ,CONTAINER_WRITE" TRUE
+
+# Add additional PERMISSION in the ACL lists of the four role contexts
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/Role=${ROLE}1" "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_READ,ACL_WRITE" FALSE
+
+# Add additional PERMISSION in the ACL lists of the four role contexts
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/Role=${ROLE}1" "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_DEFAULT,MEMBERSHIP_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/$GROUP/Role=${ROLE}1" "$USER1_SUBJECT" "$USER1_ISSUER" "ALL" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/Role=${ROLE}2" "$USER1_SUBJECT" "$USER1_ISSUER" "ACL_DEFAULT,ATTRIBUTES_WRITE" FALSE
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-ACL-entry "/$vo_name/$GROUP/$GROUP/Role=${ROLE}2" "$USER1_SUBJECT" "$USER1_ISSUER" "REQUESTS_WRITE,ATTRIBUTES_READ" FALSE
+
+# Now remove the ACL entry for USER1 from the ACL of /$vo_name/$GROUP context with propagation enabled. It should be remove from also from: /$vo_name/$GROUP/${ROLE}1, /$vo_name/$GROUP/${ROLE}2, /$vo_name/$GROUP/$GROUP, /$vo_name/$GROUP/$GROUP/${ROLE}1, /$vo_name/$GROUP/$GROUP/${ROLE}2
+voms-admin --vo=$vo_name --host $voms_host --nousercert remove-ACL-entry "/$vo_name/$GROUP" "$USER1_SUBJECT" "$USER1_ISSUER" TRUE
+
+function checkHierarchy2 {
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/Role=${ROLE}1"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=${ROLE}1" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP/Role=${ROLE}1. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/Role=${ROLE}2"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/Role=${ROLE}2" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP/Role=${ROLE}2. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP/$GROUP. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP/Role=${ROLE}1"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP/Role=${ROLE}1" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP/$GROUP/Role=${ROLE}1. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+
+   echo "<BR>Checking ACL for /$vo_name/$GROUP/$GROUP/Role=${ROLE}2"
+   voms-admin --vo=$vo_name --host $voms_host get-ACL "/$vo_name/$GROUP/$GROUP/Role=${ROLE}2" > $voms_tmp
+
+   if grep -q "^($USER1_SUBJECT,$USER1_ISSUER): " $voms_tmp; then
+       doCleanUp
+       echo "Error: ACL entry not removed from /$vo_name/$GROUP/$GROUP/Role=${ROLE}2. Stop."
+       echo "<br>"
+       cat $voms_tmp
+       echo "<br>"
+       echo "Test has failed"
+       echo "<br>"
+       exit $SAME_ERROR
+   fi
+}
+
+checkHierarchy2
+
+echo "Cleaning tasks."
+echo "<br>"
+
+doCleanUp
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
@@ -97,3 +334,4 @@ rm -rf $tempo
 echo "Test OK"
 echo "</pre>"
 exit $SAME_OK
+
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Date: 01/12/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Remove default ACL entry of group                                #
+# Description of the test: Remove Default ACL entry of a group                              #
 #                                                                                           #
 # Input Parameters:                                                                         #
 #       - VO name                                                                           #                                    
@@ -28,17 +28,60 @@ rm -rf $tempo
 date
 echo "<br>"
 echo "Test VOMS-removeDefaultACL:"
+echo "<br>"
 echo "VO=$vo_name"
+echo "<br>"
 echo "group=$GROUP"
+echo "<br>"
 echo "fake user=$USER"
+echo "<br>"
 
+# Discover the subject of the user running the tests using the proxy
+EXEC_USER_SUBJECT=$(voms-proxy-info -identity -dont-verify-ac)
+if [ $? == 1 ]; then
+    echo "Cannot discover the subject of the user running the test. voms-proxy-info returned an error.Skipping the test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
 
-echo "SCENARIO: empty VO"
-voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
+# Discover the issuer for this user (this user should be granted ALL rights for the top group)
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name > $voms_tmp
+if [ $? == 1 ]; then
+    echo "Cannot fetch ACL for top group. Skipping test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+EXEC_USER_ISSUER=$(grep "$EXEC_USER_SUBJECT" $voms_tmp | head -1 | cut -f 2 -d ',' | cut -f 1 -d ')')
+if [ -z "$EXEC_USER_ISSUER" ]; then
+    echo "Cannot find the CA subject. Skipping the test."
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test was skipped"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "Starting the test..."
+echo "Executed by: $EXEC_USER_SUBJECT, $EXEC_USER_ISSUER"
+
+echo "SCENARIO: Try to remove an ACL entry for a non-existent group (empty VO)"
+echo "<br>"
+
+voms-admin --vo=$vo_name --host $voms_host remove-default-ACL-entry "/"$vo_name"/"$GROUP $USER > $voms_stderr
+grep "org.glite.security.voms.admin.database.NoSuchGroupException" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message"
+    echo "Unexpected error when trying to remove a default ACL entry for a non-existent group."
     echo "<br>"
     cat $voms_stderr
     echo "<br>"
@@ -47,44 +90,100 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "SCENARIO: Create group <$GROUP> and add ACL entries"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
-voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for group" $voms_stderr > /dev/null
+echo "SCENARIO: Create a group /$vo_name/$GROUP, setup a default ACL and test removal effect."
+echo "<br>"
 
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Incorrect error message"
-    echo "<br>"
-    cat $voms_stderr
-    echo "<br>"
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP
 
-voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW $OP $USER
-voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER
+voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "$EXEC_USER_SUBJECT" "$EXEC_USER_ISSUER" ALL
 
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp
-grep "$user_subject" $voms_tmp > /dev/null
+ACE_RIGHTS=( CONTAINER_READ MEMBERSHIP_READ ACL_READ REQUESTS_READ ATTRIBUTES_READ CONTAINER_WRITE MEMBERSHIP_WRITE ACL_WRITE REQUESTS_WRITE ATTRIBUTES_WRITE ACL_DEFAULT CONTAINER_READ)
 
- if [ $? == 0 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error removing the ACL"
+COUNTER=0
+while [ $COUNTER -lt 11 ]; do
+   voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER" ${ACE_RIGHTS[COUNTER]}
+   COUNTER=$[$COUNTER+1]
+done
+
+COUNTER=100
+while [ $COUNTER -lt 111 ]; do
+   voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER" ${ACE_RIGHTS[COUNTER-100]}
+   COUNTER=$[$COUNTER+1]
+done
+
+echo "Create subgroup that should inherit all ACEs"
+voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP"/"del_test_group
+
+echo "<BR>Checking default ACL count for parent"
+voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_tmp
+if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then 
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Missing default ACL entry for the parent"
     echo "<br>"
     cat $voms_tmp
     echo "<br>"
     echo "Test has failed"
     echo "<br>"
     exit $SAME_ERROR
- fi
+fi
 
-echo "Cleaning tasks"
+echo "<BR>Checking ACL count for del_test_group"
+voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP"/"del_test_group > $voms_tmp
+if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
+    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Missing ACL entry for the subgroup immediately after creation"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "<BR>Start removing entries from the Default ACL of the parent"
+
+COUNTER=0
+while [ $COUNTER -lt 11 ]; do
+
+  voms-admin --vo=$vo_name --host $voms_host --nousercert remove-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER"
+  voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_tmp
+
+  if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne $[23-$COUNTER-1] ]; then
+      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
+      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+      echo "Missing default ACL entry for the parent"
+      echo "<br>"
+      cat $voms_tmp
+      echo "<br>"
+      echo "Test has failed"
+      echo "<br>"
+      exit $SAME_ERROR
+  fi
+
+  voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP"/"del_test_group > $voms_tmp
+  if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then
+      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
+      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+      echo "Missing ACL entry for the subgroup immediately after creation"
+      echo "<br>"
+      cat $voms_tmp
+      echo "<br>"
+      echo "Test has failed"
+      echo "<br>"
+      exit $SAME_ERROR
+  fi
+
+  COUNTER=$[$COUNTER+1]
+done
+
+echo "Cleaning tasks."
 echo "<br>"
- 
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
+voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
@@ -92,3 +191,4 @@ rm -rf $tempo
 echo "Test OK"
 echo "</pre>"
 exit $SAME_OK
+
