*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-dbg b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-dbg
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-dbg
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-dbg
@@ -26,6 +26,8 @@ source $SAME_SENSOR_HOME/tests/pr_config_file
 
 OPTION="debug"
 rm -rf $voms_tmp
+rm -rf $tempo
+
 
 echo
 date
@@ -33,16 +35,16 @@ echo "VOMS-PROXY-INIT: check option - $OPTION"
 
 echo "1. Create new user and proxy"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -cert $USERCERT -key $USERKEY -pwstdin < $PWS 1> $tempo
 
 if [ $? = 0 ]; then
-   echo "Test is OK"
-   #exit $SAME_OK
+   echo "OK"
 else 
-   echo "Test is failed"
+   echo "Test is failed, exit code=1"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
 fi
+
 
 echo "2. Check proxy info"
 echo "2.1.Extract by openssl from usercert.pem"
@@ -60,6 +62,40 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+
+echo "3. Check debug info"
+cat $tempo
+
+grep "Detected Globus version: 22" $tempo
+
+if [ $? = 0 ]; then
+   echo "OK"
+else 
+   echo "Test is failed"
+   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+   exit $SAME_ERROR
+fi
+
+grep "Unspecified proxy version, settling on Globus version: 2" $tempo
+
+if [ $? = 0 ]; then
+   echo "OK"
+else 
+   echo "Test is failed"
+   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+   exit $SAME_ERROR
+fi
+grep "Number of bits in key :512" $tempo
+
+if [ $? = 0 ]; then
+   echo "OK"
+else 
+   echo "Test is failed"
+   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+   exit $SAME_ERROR
+fi
+
+
 echo "Test is OK"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-ign b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-ign
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-ign
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-ign
@@ -32,35 +32,41 @@ date
 echo "VOMS-PROXY-INIT: check option - $OPTION"
 
 
-echo "1. Create new user and proxy"
+echo "1. Create new user and proxy with warning"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 
-if [ $? = 0 ]; then
-   echo "Test is OK"
-   #exit $SAME_OK
-else 
-   echo "Test is failed"
-   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-   exit $SAME_ERROR
-fi
-
-echo "2. Check proxy info"
-echo "2.1.Extract by openssl from usercert.pem"
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-echo "DN=$user_subject"
-
-echo "2.2. Execute voms-proxy-info"
-voms-proxy-info > $voms_tmp
-
-echo "2.3. Check user DN"
-grep "$user_subject" $voms_tmp
-
-if [ $? == 1 ]; then
-    echo "Test has failed"
+voms-proxy-init -voms $vo_name -vomses $VOMSES -valid 200:59 -cert $USERCERT -key $USERKEY -pwstdin < $PWS 2> $voms_tmp
+if [ $? = 1 ]; then
+    echo "Test is failed, exit code=1"
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+
+cat $voms_tmp
+
+grep "Warning" $voms_tmp
+
+if [ $? = 0 ]; then
+   echo "OK, Warning exists"
+else
+    echo "Test is failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+            
+echo "2. Create proxy with option -$OPTION"
+            
+voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -valid 200:59   -cert $USERCERT -key $USERKEY -pwstdin < $PWS 2> $voms_tmp
+
+grep "Warning" $voms_tmp
+            
+if [ $? = 0 ]; then
+    echo "Test is failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "No warnings"                 
+
 echo "Test is OK"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-noreg b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-noreg
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-noreg
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-noreg
@@ -24,6 +24,13 @@ echo "<pre>"
 export voms_host=$1
 source $SAME_SENSOR_HOME/tests/pr_config_file
 
+function clearTask {
+echo "Create normal proxy, for delete user"
+voms-proxy-init -voms $vo_name -vomses $VOMSES  -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+echo "Delete user"
+voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+}
+
 OPTION="noregen"
 rm -rf $voms_tmp
 
@@ -39,47 +46,51 @@ voms-admin --vo=$vo_name -h $voms_host create-user $USER
 echo "1.1. voms-proxy-destroy"
 voms-proxy-destroy
 
-echo "1.2. Create proxy with option -noregen"
-voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -noregen -pwstdin  2> $voms_tmp < $PWS
-#echo "Command result:"
-#cat $voms_tmp
+echo "1.2. Create normal VOMS proxy"
+voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY  -pwstdin < $PWS
+echo "voms-proxy-info:"
+voms-proxy-info
 
-grep "Failed to find valid user certificate!" $voms_tmp
-#grep "Unable to find user certificate" $voms_tmp
+echo "1.3. Create proxy with option -noregen"
+voms-proxy-init -voms $vo_name -vomses $VOMSES  -noregen #cert $USERCERT -key $USERKEY -noregen #"-$OPTION #  -pwstdin < $PWS
 
-if [ $? = 0 ]; then
-   echo "Step  is OK"
-else 
-   echo "Test is failed"
-   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-   exit $SAME_ERROR
+if [ $? == 1 ]; then
+    #echo "Exit code=$?"
+    echo "Test has failed, exit code=1"
+    clearTask
+    exit $SAME_ERROR
 fi
 
-echo "1.3. Create normal VOMS proxy"
-voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -valid "11:11" -pwstdin < $PWS
-
-echo "1.4. Create proxy with option -noregen"
-voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -$OPTION -pwstdin < $PWS
-
+echo "voms-proxy-info:"
+voms-proxy-info > $voms_tmp
 
 echo "2. Check proxy info"
+voms-proxy-info > $voms_tmp
+
 echo "2.1.Extract by openssl from usercert.pem"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 echo "DN=$user_subject"
 
-echo "2.2. Execute voms-proxy-info"
-voms-proxy-info > $voms_tmp
-
-echo "2.3. Check user DN"
+echo "2.2. Check user DN"
 grep "$user_subject" $voms_tmp
 
 if [ $? == 1 ]; then
     echo "Test has failed"
-    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    clearTask
+    exit $SAME_ERROR
+fi
+echo "2.2. Check /CN=proxy/CN=proxy"
+
+grep "/CN=proxy/CN=proxy" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    clearTask
     exit $SAME_ERROR
 fi
 echo "Test is OK"
-voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+clearTask
+
 echo "</pre>"
 exit $SAME_OK
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-vers b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-vers
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-vers
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-vers
@@ -35,9 +35,9 @@ voms-proxy-init -voms $vo_name  -$OPTION
 
 if [ $? = 0 ]; then
    echo "Test is OK"
-   #exit $SAME_OK
+   exit $SAME_OK
 else 
-   echo "Test is failed"
+   echo "Test is failed, exit code=1"
    exit $SAME_ERROR
 fi
 echo "</pre>"
