*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-addMember b/org.glite.testsuites.ctb/VOMS/tests/VOMS-addMember
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-addMember
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-addMember
@@ -14,8 +14,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -24,118 +22,99 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-addMember - started, VO=$vo_name, User=$USER, Group=$GROUP"
+echo "<br>"
+echo "test VOMS-addMember:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Group=$GROUP"
+echo "<br>"
+echo "User=$USER"
+echo "<br>"
 
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 
-echo "DN=$user_subject"
-echo "SCENARIO 1: VO - empty"
-
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "Add non existing user in non existing group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Noncorrect diagnose: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "Diag  - correct"
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Create group $GROUP"
-
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-echo "Group has created, again add member"
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
+echo "Add non existing user in group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
-
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Noncorrect diagnose <"
-   cat $voms_stderr
-   echo ">"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "Diag  - correct"
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Create user"
-
+echo "SCENARIO: Create user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-
-echo "User has created, again add member to group"
-
+echo "Add user in group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER
-
-echo "Check members list"
 voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp
-#echo "Members list:"
-#cat $voms_tmp
-grep "$user_subject" $voms_tmp
+grep "$user_subject" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Member  not created"
-   echo "LIST:<"
-   cat $voms_tmp
-   echo ">"
-   echo "DN=$user_subject"
-   echo "Test has failed"
-   exit $SAME_ERROR
-fi
-echo "Check groups of this user"
-
-voms-admin --vo=$vo_name -h $voms_host  list-user-groups $USER > $voms_tmp
-
-grep "$GROUP" $voms_tmp
-
-if [ $? == 1 ]; then
-   echo "Not exist expected group for this user:<<"
-   cat $voms_tmp
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error when adding user to group:"
+    echo "<br>"
+    cat $voms_tmp
+    echo "Test has failed"
+    echo
+    exit $SAME_ERROR
 fi
 
-
-echo "SCENARIO 2: User exist as member"
-echo "Add member"
-
+echo "SCENARIO: User is already a member of the group"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
-
-grep "is already a member of group" $voms_stderr
+grep "is already a member of group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Nonexpected diagnose:<<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Test - Ok, leave empty VO"
-
-echo "Remove group member"
+echo "Cleaning tasks"
 
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
-echo "Delete group"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-echo "Delete user"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test - OK"
+echo "Test OK"
 echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-assignRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-assignRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-assignRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-assignRole
@@ -5,17 +5,15 @@
 #                                                                                           #
 # Input Parameters:                                                                         #
 #       - VO name                                                                           #
-#       - User certificate file path                                                       #
+#       - User certificate file path                                                        #
 #       - VO host name                                                                      #
 #       - Role                                                                              #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
 #       - 1 configured VO                                                                   #
 #                                                                                           #
-###########################################################################################
+#############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -24,102 +22,107 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
 
-echo ""
 date
-echo "test VOMS-assignRole - started, VO=$vo_name, Role=$ROLE, Group=$GROUP User=$USER"
+echo "<br>"
+echo "test VOMS-assignRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
+echo "Group=$GROUP"
+echo "<br>"
+echo "User=$USER"
+echo "<br>"
 
-echo "SCENARIO: VO - empty"
-
-echo "Assign nonexisting Role to nonexisting user in nonexisting group"
-
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "Assign non existing role of non existing user in non existing group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
+    echo "Incorrect error message:"
+    echo "<br>"
     cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create new Role"
+echo "SCENARIO: Create new role"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
-echo "OK, Again assign Role"
+echo "Assign role $ROLE in group $GROUP (group doesn't exist)"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
-if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
-    cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
-fi
-
-echo "OK, Create new group"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-echo "Again assign Role"
-voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message:"
+    echo "<br>"
     cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create user"
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
+echo "Assign role $ROLE in group $GROUP (user doesn't exist)"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Create user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-
-echo "Again assign Role"
+echo "Assign role $ROLE in group $GROUP (user doesn't have the role)"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER
-
-echo "List user roles:"
 voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER > $voms_tmp
-
 expect="/"$vo_name"/"$GROUP"/Role="$ROLE
-grep "$expect" $voms_tmp
-if [ $? == 1 ]; then
-    echo "Nonexpected result: <<"
-    cat $voms_tmp
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
-fi
-
-echo "Role has assigned, verify it:"
-echo "Check user list who have this Role=$ROLE"
-
-voms-admin --vo=$vo_name -h $voms_host  list-users-with-role "/"$vo_name"/"$GROUP $ROLE > $voms_tmp
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-
-grep "$user_subject" $voms_tmp
+grep "$expect" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-    echo "No users for this Role=$ROLE: <<"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error when assigning role to user:"
+    echo "<br>"
     cat $voms_tmp
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo
+    exit $SAME_ERROR
 fi
 
 
-echo "Test - ok, leave empty VO"
-echo "Delete user"
+echo "Cleaning tasks"
+echo "<br>"
+
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-
-echo "Delete group"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-
-echo "Delete Role"
 voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crACLRole
@@ -15,8 +15,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -27,96 +25,110 @@ rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-crACLRole - started, VO=$vo_name, Role=$ROLE, fake user=$USER"
+echo "<br>"
+echo "Test VOMS-crACLRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
+echo "fake user=$USER"
+echo "<br>"
+
 oper=( all create delete add remove set-acl get-acl set-default-acl get-default-acl list )
 
-echo "SCENARIO 1: empty VO"
-
+echo "SCENARIO: empty VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER 2> $voms_stderr
-
 grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr
 
 if [ $? == 1 ]; then
-   echo "Not defined ERROR: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    echo "Error creating the role"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2: Create Role <$ROLE> and add 10 ACL entries"
+echo "SCENARIO: Create Role <$ROLE> and add 10 ACL entries"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
 for ind in 0 1 2 3 4 5 6 7 8 9
 do
  OP=${oper[ind]}
- echo "Create ACL entry <$OP > for fake user for Role $ROLE"
+ echo "Create ACL entry $OP for user for Role $ROLE"
  voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
 done
-
-echo "Again get-acl"
 voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
 
-#cat $voms_tmp
-
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 grep "$user_subject" $voms_tmp > $tempo
-#echo "Cat grep result:"
-#cat $tempo
 
 echo "Check added ACL entries"
+echo "<br>"
 ops=`cat $tempo | cut -d"|" -f3`
 echo $ops > $tempo
-
-cat $tempo
-
 for ind in 0 1 2 3 4 5 6 7 8 9
 do
  OP=${oper[ind]}
  grep $OP $tempo > /dev/null
- 
- if [ $? = 1 ]; then
-     echo "Not find added operation in LIST: <<"
-     cat $tempo
-     echo ">>, Test has failed"
-     exit $SAME_ERROR
+
+ if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Error creating the ACL"
+    echo "<br>"
+    cat $tempo
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
  fi
+ 
 done
 
-echo -e "\nSCENARIO 2: Add new operation for existing Role with assigned ACL operation"
+echo "SCENARIO: Add existing ACL entry in role $ROLE"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "list" $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null
 
-grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr
-
-if [ $? = 1 ]; then
-   echo "Non correct diagnose: <<"
-   cat $voms_stderr
-   echo ">>, Test has failed"
-   exit $SAME_ERROR
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Check diagnose for noncorrect operation name <lllist>:"
+echo "SCENARIO: Try to create an ACL entry for an unknown operation"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "lllist" $USER 2> $voms_stderr
+grep "Unknown operation:" $voms_stderr > /dev/null
 
-#cat $voms_stderr
-grep "Unknown operation:" $voms_stderr
-
-if [ $? = 1 ]; then
-   echo "Non correct diagnose: <<"
-   cat $voms_stderr
-   echo ">>, Test has failed"
-   exit $SAME_ERROR
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Clear VO"
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+echo "Cleaning tasks"
+echo "<br>"
 
+voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crDefaultACL b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crDefaultACL
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crDefaultACL
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crDefaultACL
@@ -15,8 +15,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 export voms_host=$1
@@ -27,96 +25,107 @@ rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-crDefaultACL - started, VO=$vo_name, group=$GROUP, fake user=$USER"
+echo "<br>"
+echo "Test VOMS-crDefaultACL:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "group=$GROUP"
+echo "<br>"
+echo "fake user=$USER"
+echo "<br>"
+
 oper=( all create delete add remove set-acl get-acl set-default-acl get-default-acl list )
 
-echo "SCENARIO 1: empty VO"
-
+echo "SCENARIO: empty VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW $OP $USER 2> $voms_stderr
-#cat $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Not defined ERROR: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2: Create group <$GROUP> and add 10 ACL entries"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
+echo "SCENARIO: Create group <$GROUP> and add 10 ACL entries"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
 for ind in 0 1 2 3 4 5 6 7 8 9
 do
  OP=${oper[ind]}
- echo "Create ACL entry <$OP > for fake user in group $GROUP"
+ echo "Create ACL entry $OP for user in group $GROUP"
  voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW $OP $USER
 done
-
-echo "Check added default operations for group"
 voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp
 
-#cat $voms_tmp
-
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 grep "$user_subject" $voms_tmp > $tempo
-#echo "Cat grep result:"
-#cat $tempo
 
 echo "Check added ACL entries"
+echo "<br>"
 ops=`cat $tempo | cut -d"|" -f3`
 echo $ops > $tempo
-
-cat $tempo
-
 for ind in 0 1 2 3 4 5 6 7 8 9
 do
  OP=${oper[ind]}
  grep $OP $tempo > /dev/null
- 
- if [ $? = 1 ]; then
-     echo "Not find added operation in LIST: <<"
-     cat $tempo
-     echo ">>, Test has failed"
-     exit $SAME_ERROR
+
+ if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error creating the ACL"
+    echo "<br>"
+    cat $tempo
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
  fi
 done
 
-echo -e "\nSCENARIO 2: Add new operation for existing group with assigned ACL operation"
+echo "SCENARIO: Add existing ACL entry in group $GROUP"
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW "list" $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null
 
-grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr
-
-if [ $? = 1 ]; then
-   echo "Non correct diagnose: <<"
-   cat $voms_stderr
-   echo ">>, Test has failed"
-   exit $SAME_ERROR
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
-echo "Check diagnose for noncorrect operation name <lllist>:"
+
+echo "SCENARIO: Try to create an ACL entry for an unknown operation:"
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW "lllist" $USER 2> $voms_stderr
+grep "Unknown operation:" $voms_stderr > /dev/null
 
-#cat $voms_stderr
-grep "Unknown operation:" $voms_stderr
-
-if [ $? = 1 ]; then
-   echo "Non correct diagnose: <<"
-   cat $voms_stderr
-   echo ">>, Test has failed"
-   exit $SAME_ERROR
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Clear VO"
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+echo "Cleaning tasks"
+echo "<br>"
 
+voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crGroup b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crGroup
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crGroup
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crGroup
@@ -13,8 +13,6 @@
 #                                                                                           #
 ###########################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,51 +21,59 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-
-echo ""
 date
-echo "VOMS-crGroup - started, VO=$vo_name, group=$GROUP"
-echo "             SCENARIO 1, group not exist...                 "
+echo "<br>"
+echo "Test VOMS-crGroup:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$GROUP"
+echo "<br>"
 
+echo "SCENARIO: Group doesn't exist"
+echo "<br>"
 echo "Create new group"
-voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name" "/$GROUP"
-
-echo "Check list groups"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"
 voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp
-
-
-echo "Check list groupnames"
-grep "$GROUP" $voms_tmp        #> /dev/null
-
+echo "Check group"
+grep "$GROUP" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Group  not created LIST:<"
-   cat $voms_tmp
-   echo "> Test has failed"
-   exit $SAME_ERROR
-fi
-echo "OK"
-echo "           SCENARIO 2:  group exist            "
-echo "Create new group"
-voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name" "/$GROUP" 2> $voms_stderr
-
-echo "OK, check stderr"
-# Check error message is correct
-#cat $voms_stderr
-
-grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr    # > /dev/null
-
-if [ $? == 1 ]; then
-    echo "Not defined ERROR<"
-    cat $voms_stderr
-    echo ">, Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name"/"$GROUP"
+    echo "Error creating the group"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
     exit $SAME_ERROR
 fi
-                
-echo "OK,  Cleaning tasks: Leave VO empty "
-echo "Remove group"
+
+echo "SCENARIO 2: Group already exists in the VO"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP" 2> $voms_stderr
+grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+   voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name"/"$GROUP"
+   echo "Incorrect error message:"
+   echo "<br>"
+   cat $voms_stderr
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+echo "Cleaning tasks"
+echo "<br>"
+
 voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name"/"$GROUP"
-echo "Test is OK"
+rm -rf $voms_tmp
+rm -rf $voms_stderr
+
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crRole
@@ -13,8 +13,6 @@
 #                                                                                           #
 ###########################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,56 +21,59 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
 date
-echo "test VOMS-crRole - started, VO=$vo_name, Role=$ROLE"
+echo "<br>"
+echo "Test VOMS-crRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
 
-echo "SCENARIO 1: Role not exists"
-
-
+echo "SCENARIO: Role doesn't exist"
+echo "<br>"
 echo "Create new Role"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
-echo "Check list roles"
 voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
-
 echo "Check role"
-grep "$ROLE" $voms_tmp  # > /dev/null
-
+grep "$ROLE" $voms_tmp   > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Role not created,LIST:<"
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Error creating the role"
+    echo "<br>"
     cat $voms_tmp
-    echo ">,  Test has failed"
-   exit $SAME_ERROR
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
-echo "Scenario 1 - OK"
 
-echo "SCENARIO 2: Role exists"
-
-echo "Create new Role"
+echo "SCENARIO 2: Role already exists in the VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE 2> $voms_stderr
-#echo "STDERR:"
-#cat $voms_stderr
-
-grep "org.glite.security.voms.service.AlreadyExist" $voms_stderr  # > /dev/null
+grep "org.glite.security.voms.service.AlreadyExist" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Not defined diagnose:<<"
+   voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+   echo "Incorrect error message:"
+   echo "<br>"
    cat $voms_stderr
-   echo ">> Test has failed"
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
-echo "Scenario 2 - OK"
-echo "Remove Role"
+echo "Cleaning tasks"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
-
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crUserNocert b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crUserNocert
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-crUserNocert
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-crUserNocert
@@ -12,8 +12,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,86 +21,96 @@ source $SAME_SENSOR_HOME/tests/config_file
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
+
 DN="/Fake User DN"
 CN="/Fake User CN"
 EMAIL="fakeuser@cern.ch"
 
-echo ""
 date
-echo "VOMS-crUserNocert - started, VO=$vo_name, User=$DN"
+echo "<br>"
+echo "Test VOMS-crUserNocert:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "User=$DN"
+echo "<br>"
 
-
-echo "SCENARIO 1: User doesn't exist"
+echo "SCENARIO: User doesn't exist"
+echo "<br>"
 echo "Create new user"
-
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$DN" "$CA" "$CN" "$EMAIL"
-
-echo "Check list users"
-
 voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp
-
-#cat $voms_tmp
-
-echo "Check Subject name, "
-
-grep "$DN" $voms_tmp > $tempo
-
+echo "Check DN"
+echo "<br>"
+grep "$user_subject" $voms_tmp > $tempo
 
 if [ $? == 1 ]; then
-   echo "User not created: LIST:<<"
-   cat $voms_tmp
-   echo ">>"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$DN" "$CA"
+   echo "Error creating the user: wrong DN"
+   echo "<br>"
+   cat $tempo
+   echo "<br>"
    echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "DN - correct"
-fi
-
-echo "Check CN, "
-grep "$CN" $tempo  > /dev/null
-
-if [ $? == 0 ]; then 
-    echo "CN - correct!"
-else 
-    echo "User CN - noncorrect, test has failed"
-    exit $SAME_ERROR
-fi
-
-echo "Check CA, "
-grep "$CA" $tempo  > /dev/null
-
-if [ $? == 0 ]; then 
-    echo "CA - correct!"
-else
-   echo "CA - noncorrect, test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
-echo "SCENARIO 1 - OK"
 
-echo "SCENARIO 2: Create user who already exists in the VO"
+echo "Check CN"
+echo "<br>"
+grep "$user_CN" $tempo  > /dev/null
+
+if [ $? == 1 ]; then
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$DN" "$CA"
+   echo "Error creating the user: wrong CN"
+   echo "<br>"
+   cat $tempo
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+echo "Check CA"
+echo "<br>"
+grep "$user_CA" $tempo  > /dev/null
+
+if [ $? == 1 ]; then
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$DN" "$CA"
+   echo "Error creating the user: wrong CA"
+   echo "<br>"
+   cat $tempo
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+
+echo "SCENARIO: User already exists in the VO"
+echo "<br>"
 rm -rf $voms_stderr
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$DN" "$CA" "$CN" "$EMAIL" 2> $voms_stderr
-
-# Check error message is correct
-cat $voms_stderr
-
 grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null
-# Add exit code if OK or failure
 
 if [ $? == 1 ]; then
-    echo "Not defined ERROR:<<"
-    cat $voms_stderr
-    echo >">, Test has failed"
-    exit $SAME_ERROR
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$DN" "$CA"
+   echo "Incorrect error message:"
+   echo "<br>"
+   cat $voms_stderr
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
 fi
 
-echo "Cleaning tasks: Leave VO empty "
-echo "Remove user"
-
+echo "Cleaning tasks"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$DN" "$CA"
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
-echo "Test is OK"
+
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delGroup b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delGroup
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delGroup
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delGroup
@@ -4,17 +4,15 @@
 # Description of the test: Delete group for VO                                              #
 #                                                                                           #
 # Input Parameters:                                                                         #
-#       - VO name                                                                           #                       #
+#       - VO name                                                                           #
 #       - VO host name                                                                      #
 #       - Group name                                                                        #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
 #       - 1 configured VO                                                                   #
 #                                                                                           #
-###########################################################################################
+#############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,53 +21,56 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
 date
-echo "test VOMS-delGroup - started, VO=$vo_name, Group=$GROUP" 
+echo "<br>"
+echo "Test VOMS-delGroup:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$GROUP"
+echo "<br>"
 
-
-echo "            SCENARIO 1: group - not exist             "
-
-
-echo "Delete group"
+echo "SCENARIO: Group doesn't exist"
+echo "<br>"
+echo "Delete Group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP" 2> $voms_stderr
-
-#echo "check error message:<<"
-#cat $voms_stderr
-#echo ">>"
-
-grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr  # > /dev/null
+grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Not defined ERROR<"
-    cat $voms_stderr
-    echo ">, Test has failed"
-    exit $SAME_ERROR
+   echo "Incorrect error message:"
+   echo "<br>"
+   cat $voms_stderr
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
 fi
 
-echo "           SCENARIO 2: Group exists              "
-
-echo "Create new group"
-voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name" "/$GROUP"
-
-echo "Delete this group"
+echo "SCENARIO: Group already exists in the VO"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
-
-
-echo "Check if this group exists already"
 voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp
-
 grep "$GROUP" $voms_tmp > /dev/null
 
-if [ $? == 0 ]; then 
-    echo "Group not removed! Test has failed"
-    exit $SAME_ERROR
+if [ $? == 0 ]; then
+   echo "Error deleting the group"
+   echo "<br>"
+   cat $voms_tmp
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
 fi
+
+echo "Cleaning tasks"
+echo "<br>"
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "    Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delRole
@@ -11,10 +11,8 @@
 #	- VOMS server                                                                       #
 #       - 1 configured VO                                                                   #
 #                                                                                           #
-###########################################################################################
+#############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,56 +21,58 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-
-echo ""
 date
-echo "VOMS-delRole - started, VO=$vo_name, Role=$ROLE"
-echo "             SCENARIO 1, Role  not exist...                 "
+echo "<br>"
+echo "Test VOMS-delRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
 
-
-echo "Delete  Role"
+echo "SCENARIO: Role doesn't exist"
+echo "<br>"
+echo "Delete Role"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE 2> $voms_stderr
-
-#echo "OK, check stderr: <<"
-#cat $voms_stderr
-#echo ">>"
-
-grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr  # > /dev/null
+grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr   > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Not defined ERROR: <<"
-    cat $voms_stderr
-    echo ">>, Test has failed"
-    exit $SAME_ERROR
-fi
-                
-
-echo "               SCENARIO 2  Role exists          "
-echo "Create new Role"
-voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
-echo "Delete this Role"
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-
-echo "Check list roles"
-voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
-
-grep "$ROLE" $voms_tmp > /dev/null
-
-
-if [ $? == 0 ]; then
-   echo "Role not deleted, LIST:<<"
-   cat $voms_tmp
-   echo ">>,     Test has failed"
+   echo "Incorrect error message:"
+   echo "<br>"
+   cat $voms_stderr
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
+
+echo "SCENARIO: Role already exists in the VO"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
+voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
+grep "$ROLE" $voms_tmp > /dev/null
+
+if [ $? == 0 ]; then
+   echo "Error deleting the role"
+   echo "<br>"
+   cat $voms_tmp
+   echo "<br>"
+   echo "Test has failed"
+   echo "<br>"
+   exit $SAME_ERROR
+fi
+
+echo "Cleaning tasks"
+echo "<br>"
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
 
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delUser b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delUser
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-delUser
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-delUser
@@ -16,8 +16,6 @@
 #                                                                                           #
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -26,54 +24,62 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-delUser - started, VO=$vo_name, User=$USER"
+echo "<br>"
+echo "Test VOMS-delUser:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "User=$USER"
+echo "<br>"
 
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 
 echo "DN=$user_subject"
+echo "<br>"
 
-echo "SCENARIO 1: User doesn't exist"
-
-echo "Remove  not existing user"
+echo "SCENARIO: User doesn't exist"
+echo "<br>"
+echo "Remove non existing user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER 2> $voms_stderr
-#cat $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr # > /dev/null
+grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr  > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"    
-    cat $voms_stderr
-    echo ">> Test has failed"
+   echo "Incorrect error message:"
+   echo "<br>"
+   cat $voms_stderr
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2, Create and then remove user"
+echo "SCENARIO: User already exists in the VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-
-echo "Remove created user"
+echo "Remove existing user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-
-
-echo "Check list users after user deletion"
 voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp
-
-
-grep "$user_subject" $voms_tmp # > /dev/null
-
+grep "$user_subject" $voms_tmp  > /dev/null
 
 if [ $? == 0 ]; then
-   echo "User not deleted: <<"
+    echo "Error deleting the user"
+    echo "<br>"
     cat $voms_tmp
-    echo ">>,    Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
-   rm -rf $voms_tmp
-   rm -rf $voms_stderr
- 
-   echo "Test is OK"
-   exit $SAME_OK
 
+
+echo "Cleaning tasks"
+echo "<br>"
+
+rm -rf $voms_tmp
+rm -rf $voms_stderr
+
+echo "Test OK"
+echo "</pre>"
+exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-genGM b/org.glite.testsuites.ctb/VOMS/tests/VOMS-genGM
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-genGM
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-genGM
@@ -14,8 +14,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -23,127 +21,102 @@ export voms_host=$1
 source $SAME_SENSOR_HOME/tests/config_file
 
 export mkgrid="/opt/edg/libexec/edg-mkgridmap"
-#export conf="$HOME/SAM/SAME/gridmap.conf"
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-genGM - started, VO=$vo_name, CA1=$CA, CA2=$CA_CERN"
+echo "<br>"
+echo "Test VOMS-genGM:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "CA1=$CA"
+echo "<br>"
+echo "CA2=$CA_CERN"
+echo "<br>"
+
 user1="DN_USER1"
 user2="DN_USER2"
 
-echo "Error stderr" > $voms_stderr
-
-echo "Step 1: Create grid-mapfile for empty VO"
-
+echo "SCENARIO: Create gridmap file for empty VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host list-users 2> $voms_stderr
-
 grep "No users are returned" $voms_stderr
 
 if [ $? == 1 ]; then
-   echo "VO - not empty: LIST:<<"
-   cat $voms_stderr
-   echo ">> Test has failed"
-   exit $SAME_ERROR
+    echo "The VO is not empty. Test needs an empty VO"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Generate grid-mapfile for empty VO"
-$mkgrid/edg-mkgridmap.pl --conf=$GRIDMAP --output=$voms_tmp
+echo "Generate gridmap file for empty VO"
+echo "<br>"
+$mkgrid --conf=$GRIDMAP --output=$voms_tmp
 
-#/opt/edg/sbin/edg-mkgridmap --output=$voms_tmp
-echo "Check grid-mapfile"
-
+echo "Check gridmap file"
+echo "<br>"
 if test -s $voms_tmp
 then
-   echo "Non zero file size"
+   echo "gridmap file should be empty for an empty VO"
+   echo "<br>"
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
-else
-   echo "Zero file size, continue"
 fi
 
-echo "Step 2: Create one fake user"
-
+echo "SCENARIO: Create gridmap file for one user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
-
 rm -rf $tempo
-#/opt/edg/sbin/edg-mkgridmap --output=$voms_tmp
-$mkgrid/edg-mkgridmap.pl --conf=$GRIDMAP --output=$voms_tmp
-echo "grid-mapfile:"
+$mkgrid --conf=$GRIDMAP --output=$voms_tmp
 usr=`cat $voms_tmp | cut -d" " -f1`
 acc=`cat $voms_tmp | cut -d" " -f2`
-echo "User=$usr"
-echo "Account=$acc"
-
-#echo "$user1" > $voms_tmp
 grep "$user1" $voms_tmp > $tempo
-echo "Check user DN"
+
 if [ $? == 1 ]; then
-   echo "User DN not found in grid-mapfile:<<"
+   echo "Incorrect User DN in gridmap file"
+   echo "<br>"
    cat $voms_tmp
-   echo ">> Test has failed"
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
-echo "OK"
-echo "Check user account"
-#ACCOUNT=".dteam"
 
 if [ $acc != $ACCOUNT ]; then
-   echo "Noncorect mapped user account<<"
+   echo "Incorrect user account in gridmap file"
+   echo "<br>"
    echo $acc
-   echo ">> Test has failed"
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
-echo "OK"
 
-#cho "User DN has found in grid-mapfile"
-
-echo "Step 3: Create second user with the same DN, but another CA"
-
+echo "SCENARIO: Create gridmap file for same user DN but different CA"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA_CERN" "CN-User1" "user1@cern.ch"
-
-echo "Generate grid-mapfile"
-
-#/opt/edg/sbin/edg-mkgridmap --output=$voms_tmp
-$mkgrid/edg-mkgridmap.pl --conf=$GRIDMAP --output=$voms_tmp
-echo "grid-mapfile:"
-cat $voms_tmp
-
-
-echo "Check grid-mapfile"
-#echo "$user1" > $voms_tmp
-
-grep "$user1" $voms_tmp > $tempo
-
-if [ $? == 1 ]; then
-   echo "User DN not found in grid-mapfile:<<"
-   cat $voms_tmp
-   echo ">> Test has failed"
-   exit $SAME_ERROR
-fi
-echo "User DN has found in grid-mapfile"
+$mkgrid --conf=$GRIDMAP --output=$voms_tmp
 lines=`grep -c "$user1" $voms_tmp` 
-echo "Find $lines lines"
 
 if [ $lines != 1 ]; then
-   echo "More then 1 entry in gridmap file"
+   echo "Incorrect gridmap file"
+   echo "<br>"
+   cat $voms_tmp
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
-
-
-echo "Clear Created users"
 voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
 voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA_CERN"
 
+
 UMAX=3
-
-echo "Step 4: Generate $UMAX users and $UMAX entries in grid-mapfile"
-
-echo "4.1. Create $UMAX users in VO"
+echo "SCENARIO: Create gridmap file for $UMAX users"
+echo "<br>"
 counter=0
 while [ $counter -lt $UMAX ]; do
   user="DN User"$counter
@@ -151,23 +124,7 @@ while [ $counter -lt $UMAX ]; do
   let counter=counter+1
 done
 
-echo "4.2. Generate grid-mapfile for $UMAX users"
-counter=0
-#echo "" > $voms_tmp
-
-$mkgrid/edg-mkgridmap.pl --conf=$GRIDMAP --output=$voms_tmp
-#echo "grid-mapfile:"
-#cat $voms_tmp
-#/opt/edg/sbin/edg-mkgridmap --output=$voms_tm
-
-#while [ $counter -lt $UMAX ]; do
-#  user="DN User"$counter
-#  echo "$user " >> $voms_tmp
-#  let counter=counter+1
-#done
-
-echo "4.3. Check grid-mapfile"
-#cat $voms_tmp
+$mkgrid --conf=$GRIDMAP --output=$voms_tmp
 
 counter=0
 while [ $counter -lt $UMAX ]; do
@@ -175,15 +132,16 @@ while [ $counter -lt $UMAX ]; do
   grep "$user" $voms_tmp > /dev/null
   
   if [ $? == 1 ]; then
-   echo "User DN=$user  not found in grid-mapfile:<<"
+   echo "User DN=$user is not mapped in the gridmap file"
+   echo "<br>"
    cat $voms_tmp
-   echo ">> Test has failed"
+   echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
   let counter=counter+1
 done
 
-echo "4.4. Remove users in VO"
 counter=0
 while [ $counter -lt $UMAX ]; do
   user="DN User"$counter
@@ -191,9 +149,13 @@ while [ $counter -lt $UMAX ]; do
   let counter=counter+1
 done
 
+echo "Cleaning tasks"
+echo "<br>"
+
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
 echo "Test is OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listDefaultACL
@@ -15,8 +15,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -27,73 +25,99 @@ rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-listDefauotACL - started, VO=$vo_name, group=$GROUP, fake user=$USER"
+echo "<br>"
+echo "Test VOMS-listDefaultACL:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "group=$GROUP"
+echo "<br>"
+echo "fake user=$USER"
+echo "<br>"
+
 op1="list"
 op2="create"
 op3="delete"
 allow="allow"
 
-echo "SCENARIO 1: empty VO"
-
+echo "SCENARIO: empty VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Not defined ERROR: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2: Create group <$GROUP> and add 3 default ACL entries"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-echo "Create ACL entry for fake user in group $GROUP"
+echo "SCENARIO: Create group <$GROUP> and add 3 default ACL entries"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op1 $USER
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op2 $USER
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op3 $USER
-
-echo "Again get-acl"
 voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp
 
-#cat $voms_tmp
-
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 grep "$user_subject" $voms_tmp > $tempo
-
-#cat $tempo
 echo "Check added ACL entries"
+echo "<br>"
 ops=`cat $tempo | cut -d"|" -f3`
 echo $ops > $tempo
 
-grep "$op1" $tempo
-if [ $? == 1 ]; then
-   echo "LIST: <<$ops>>, Test has filed"
-   exit $SAME_ERROR
-fi
-grep "$op2" $tempo
-if [ $? == 1 ]; then
-   echo "LIST: <<$ops>>, Test has filed"
-   exit $SAME_ERROR
-fi
-grep "$op3" $tempo
-if [ $? == 1 ]; then
-   echo "LIST: <<$ops>>, Test has filed"
-   exit $SAME_ERROR
-fi
+grep "$op1" $tempo > /dev/null
 
+ if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error listing the ACL"
+    echo "<br>"
+    cat $tempo
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+ fi
 
-echo "Clear VO"
+grep "$op2" $tempo > /dev/null
+
+ if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error listing the ACL"
+    echo "<br>"
+    cat $tempo
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+ fi
+
+grep "$op3" $tempo > /dev/null
+
+ if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error listing the ACL"
+    echo "<br>"
+    cat $tempo
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+ fi
+
+echo "Cleaning tasks"
+echo "<br>"
+
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listMembers b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listMembers
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listMembers
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listMembers
@@ -14,8 +14,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -24,127 +22,153 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-listMembers - started, VO=$vo_name, Group=$GROUP"
+echo "<br>"
+echo "test VOMS-listMembers:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Group=$GROUP"
+echo "<br>"
+echo "User=$USER_subject"
+echo "<br>"
 
-echo "SCENARIO 1: VO - empty"
-echo "Try list command for nonexisting group" 
-voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
-
-if [ $? == 1 ]; then
-   echo "Noncorrect diagnose <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-    echo "Diag - correct"
-fi
-
-echo "Create group $GROUP"
-voms-admin --vo=$vo_name  -h $voms_host  create-group "/"$vo_name "/"$GROUP
-
-echo "List members again"
-voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
-
-grep "No users are returned" $voms_stderr
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "List non existing members of non existing group"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Noncorrect diagnose <"
-   cat $voms_stderr
-   echo ">"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "Diag  - correct"
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
-echo "Create new users and add members to this group"
+
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name  -h $voms_host  create-group "/"$vo_name"/"$GROUP
+echo "List non existing members of group $GROUP"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
+grep "No users are returned" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Create users"
+echo "<br>"
 user1="DN_USER1"
 user2="DN_USER2"
 user3="DN_USER3"
 user4="DN_USER4"
-
-echo "Step 1: Create 4 nocert users: $user1, $user2, $user3, $user4"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user2" "$CA" "CN-User2" "user2@cern.ch"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user3" "$CA" "CN-User3" "user3@cern.ch"
 voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user4" "$CA" "CN-User4" "user4@cern.ch"
-echo "OK"
-
-echo "add this users as members to group"
+echo "Add members to group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"
-
-echo "List new 4 members this group"
+echo "List members of group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp
 
-echo "check this members list"
+grep "$user1" $voms_tmp > /dev/null
 
-grep "$user1" $voms_tmp
 if [ $? == 1 ]; then
-   echo "Member  $user2 not exist LIST:<"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error creating user $user1"
+   echo "<br>"
    cat $voms_tmp
-   echo ">"
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
-grep "$user2" $voms_tmp
+grep "$user2" $voms_tmp > /dev/null
+
 if [ $? == 1 ]; then
-   echo "Member  $user2 not exist LIST:<"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error creating user $user2"
+   echo "<br>"
    cat $voms_tmp
-   echo ">"
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
-grep "$user3" $voms_tmp
+grep "$user3" $voms_tmp > /dev/null
+
 if [ $? == 1 ]; then
-   echo "Member $user3  not exist LIST:<"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error creating user $user3"
+   echo "<br>"
    cat $voms_tmp
-   echo ">"
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
-grep "$user4" $voms_tmp
+grep "$user4" $voms_tmp > /dev/null
+
 if [ $? == 1 ]; then
-   echo "Member $user4  not exist LIST:<"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
+   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+   echo "Error creating user $user4"
+   echo "<br>"
    cat $voms_tmp
-   echo ">"
    echo "Test has failed"
+   echo "<br>"
    exit $SAME_ERROR
 fi
 
 
-echo "Test - Ok, leave empty VO"
-
-echo "Remove group members"
+echo "Cleaning tasks"
+echo "<br>"
 
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"
-
-echo "Delete group"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-
-echo "Delete users"
 voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user1 "$CA"
 voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user2 "$CA"
 voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user3 "$CA"
 voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user4 "$CA"
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test - OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserGroups b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserGroups
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserGroups
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserGroups
@@ -24,75 +24,70 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
+
 date
-echo "VOMS-listGroups - started, VO=$vo_name, user=$USER"
+echo "<br>"
+echo "Test VOMS-listUserGroups:"
+echo "VO=$vo_name"
+echo "Group=$GROUP"
+echo "User=$USER_subject"
+echo "<br>"
 
-echo "SCENARIO: empty VO"
-
-echo "List group command for empty VO:"
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "List non existing groups of non existing user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER 2> $voms_stderr
-#cat $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "User exist: <<"
-   cat $voms_stderr
-   echo ">>   Test has failed"
-   exit $SAME_ERROR
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
-echo "OK, user not exist, create new user in VO"
 
+echo "SCENARIO: Create user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-echo "List users"
-voms-admin --vo=$vo_name -h $voms_host list-users
-
+echo "List non existing groups of user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER > $voms_tmp
 mainGroup=`cat $voms_tmp`
 echo "Main group: $mainGroup" 
 
 if [ $mainGroup = "/"$vo_name ]; then
-   echo "Only main group $vo_name exists"
+   echo "VO group is always present"
 fi
 
-
-echo "OK"
-
-echo "Create new group $GROUP"
-voms-admin --vo=$vo_name  -h $voms_host create-group "/"$vo_name "/"$GROUP
-echo "List groups"
-voms-admin --vo=$vo_name  -h $voms_host list-groups
-
-echo "Add member into this group"
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name  -h $voms_host create-group "/"$vo_name"/"$GROUP
+echo "Add user as member of group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER
-
-echo "List members of this group"
-voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP
-
-echo "List user groups"
+echo "List existing group $GROUP of user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER > $voms_tmp
-cat $voms_tmp
-
-echo "Check groupname for this user"
-grep "$GROUP" $voms_tmp
+grep "$GROUP" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-   echo "No group for this user $USER: <<"
-   cat $voms_tmp
-   echo ">> Test has failed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error when listing user groups:"
+    echo "<br>"
+    cat $voms_tmp
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Leave empty VO:"
-echo "Remove group member"
-voms-admin --vo=$vo_name  -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
-
-echo "Remove group"
-voms-admin --vo=$vo_name  -h $voms_host delete-group "/"$vo_name"/"$GROUP
-echo "Remove user"
+echo "Cleaning tasks"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host delete-user $USER
-echo "Test is OK"
+voms-admin --vo=$vo_name  -h $voms_host delete-group "/"$vo_name"/"$GROUP
+echo "Test OK"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserRoles b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserRoles
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserRoles
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUserRoles
@@ -1,16 +1,16 @@
 #!/bin/bash
 # Date: 09/11/2006                                                                          #
 # Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
-# Description of the test: Remove user's Role                                               #
+# Description of the test: List roles for the specified user in VO                          #
 #                                                                                           #
 # Input Parameters:                                                                         #
 #       - VO name                                                                           #
 #       - User certificate file path                                                        #
-#       - Group                                                                             #
+#       - VO host name                                                                      #
 #       - Role                                                                              #
 # Requisites:                                                                               #
 #	- VOMS server                                                                       #
-#       - 1 configured and empty VO                                                         #
+#       - 1 configured VO                                                                   #
 #                                                                                           #
 #############################################################################################
 #                                                                                           #
@@ -23,11 +23,9 @@ source $SAME_SENSOR_HOME/tests/config_file
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-USER_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-
 date
 echo "<br>"
-echo "test VOMS-dismissRole:"
+echo "test VOMS-listUserRoles:"
 echo "<br>"
 echo "VO=$vo_name"
 echo "<br>"
@@ -40,13 +38,31 @@ echo "<br>"
 
 echo "SCENARIO: VO empty"
 echo "<br>"
-echo "Remove non existing role of non existing user in non existing group"
+echo "List non existing roles of non existing user"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role " $voms_stderr > /dev/null
+voms-admin --vo=$vo_name -h $voms_host list-user-roles $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Incorrect error message:"   
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Create user"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-user $USER
+echo "List roles (user doesn't have roles)"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host list-user-roles $USER 2> $voms_stderr
+grep "No roles are returned" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    echo "Incorrect error message:"
     echo "<br>"
     cat $voms_stderr
     echo "Test has failed"
@@ -57,12 +73,31 @@ fi
 echo "SCENARIO: Create new role"
 echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-echo "Dismiss role $ROLE in group $GROUP (group doesn't exist)"
+echo "List roles (user hasn't been assigned to role)"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
+voms-admin --vo=$vo_name -h $voms_host list-user-roles $USER 2> $voms_stderr
+grep "No roles are returned" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Assign role to user"
+echo "<br>"
+echo "Assign role $ROLE in group $GROUP (group doesn't exist)"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host assign-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
 grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
     echo "Incorrect error message:"
     echo "<br>"
@@ -75,53 +110,18 @@ fi
 echo "SCENARIO: Create new group"
 echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
-echo "Dismiss role $ROLE in group $GROUP (user doesn't exist)"
+echo "Assign role $ROLE in group $GROUP"
 echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
-
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Incorrect error message:"
-    echo "<br>"
-    cat $voms_stderr
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
-
-echo "SCENARIO: Create user"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host create-user $USER
-echo "Dismiss role $ROLE in group $GROUP (user doesn't have the role)"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-grep "does not have role" $voms_stderr  > /dev/null
-
-if [ $? == 1 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Incorrect error message:"
-    echo "<br>"
-    cat $voms_stderr
-    echo "Test has failed"
-    echo
-    exit $SAME_ERROR
-fi
-
-echo "SCENARIO: Assign role to user"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER
+voms-admin --vo=$vo_name -h $voms_host assign-role "/"$vo_name"/"$GROUP $ROLE $USER
 voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER > $voms_tmp
-grep "$ROLE" $voms_tmp > /dev/null
+expect="/"$vo_name"/"$GROUP"/Role="$ROLE
+grep "$expect" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
     voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error when assigning role to user:"
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Error when listing user roles:"
     echo "<br>"
     cat $voms_tmp
     echo "Test has failed"
@@ -129,30 +129,14 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "Dismiss role $ROLE in group $GROUP"
-echo "<br>"
-voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER
-voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER 2> $voms_stderr 
-grep "$ROLE" $voms_stderr > /dev/null
-
-if [ $? == 0 ]; then
-    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-    echo "Error when removing role from user:"
-    echo "<br>"
-    cat $voms_stderr
-    echo "Test has failed"
-    echo "<br>"
-    exit $SAME_ERROR
-fi
+echo "Cleaning tasks"
+voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
 
 echo "Cleaning tasks"
 echo "<br>"
 
-voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUsrWithRol b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUsrWithRol
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUsrWithRol
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-listUsrWithRol
@@ -11,10 +11,8 @@
 #	- VOMS server                                                                       #
 #       - 1 configured VO                                                                   #
 #                                                                                           #
-###########################################################################################
+#############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -24,102 +22,105 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
 
-echo ""
-echo "test VOMS-listUsersRole - started, VO=$vo_name, Role=$ROLE, Group=$GROUP"
+date
+echo "<br>"
+echo "test VOMS-listUsrWithRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
+echo "Group=$GROUP"
+echo "<br>"
+echo "User=$USER_subject"
+echo "<br>"
 
-echo "SCENARIO: VO - empty"
-
-echo "List users for nonexisting Role in nonexisting group"
-
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "List non existing users of non existing role in non existing group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host list-users-with-role "/"$vo_name"/"$GROUP $ROLE 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
+    echo "Incorrect error message:"
+    echo "<br>"
     cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create new Role"
+echo "SCENARIO: Create new role"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
-echo "OK, Again list users"
+echo "List non existing users of role $ROLE in non existing group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host  list-users-with-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
-if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
-    cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
-fi
-
-echo "OK, Create new group"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-echo "Again list users with  Role"
-voms-admin --vo=$vo_name -h $voms_host  list-users-with-role "/"$vo_name"/"$GROUP $ROLE 2> $voms_stderr
-grep "No users are returned" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-    echo "Noncorrect diagnose: <<"
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message:"
+    echo "<br>"
     cat $voms_stderr
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create user"
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
+echo "List non existing users of role $ROLE in group $GROUP"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host list-users-with-role "/"$vo_name"/"$GROUP $ROLE 2> $voms_stderr
+grep "No users are returned" $voms_stderr > /dev/null
+
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Create user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-
-echo "Assign Role"
 voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER
-
-echo "List user roles:"
-voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER > $voms_tmp
-
-expect="/"$vo_name"/"$GROUP"/Role="$ROLE
-grep "$expect" $voms_tmp
-if [ $? == 1 ]; then
-    echo "Nonexpected result: <<"
-    cat $voms_tmp
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
-fi
-
-echo "Role has assigned, verify it:"
-echo "Check user list who have this Role=$ROLE"
-
-voms-admin --vo=$vo_name -h $voms_host  list-users-with-role "/"$vo_name"/"$GROUP $ROLE > $voms_tmp
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-
-grep "$user_subject" $voms_tmp
+echo "List users of role $ROLE in group $GROUP"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host list-users-with-role "/"$vo_name"/"$GROUP $ROLE > $voms_tmp
+grep "$USER_subject" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-    echo "No users for this Role=$ROLE: <<"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Error when listing users with role:"
+    echo "<br>"
     cat $voms_tmp
-    echo ">>,  Test has failed"
-   exit $SAME_ERROR
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
+echo "Cleaning tasks"
+echo "<br>"
 
-echo "Test - ok, leave empty VO"
-echo "Delete user"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-
-echo "Delete group"
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-
-echo "Delete Role"
 voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
 
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeACLRole
@@ -15,8 +15,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -27,65 +25,75 @@ rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-removeACLRole - started, VO=$vo_name, Role=$ROLE, fake user=$USER"
+echo "<br>"
+echo "Test VOMS-removeACLRole:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Role=$ROLE"
+echo "<br>"
+echo "fake user=$USER"
+echo "<br>"
 
-echo "SCENARIO 1: empty VO"
-
+echo "SCENARIO: empty VO"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Not defined ERROR: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2: Create role <$ROLE> and add ACL entries"
+echo "SCENARIO: Create role <$ROLE> and add ACL entry"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
-
-
-echo "Again remove-acl-entry"
-
 voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for role" $voms_stderr > /dev/null
 
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for role" $voms_stderr
 if [ $? == 1 ]; then
-   echo "Not correct diagnose: <<$voms_stderr>>, Test has filed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create ACL entry for fake user for Role $ROLE"
 voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
-
-echo "Again remove-acl-entry"
 voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER
 
-echo "-------- Extract user subject-name by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-
-echo "Check result using get-acl"
-
 voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
+grep "$user_subject" $voms_tmp > /dev/null
 
-grep "$user_subject" $voms_tmp
+ if [ $? == 0 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
+    echo "Error removing the ACL"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+ fi
 
-if [ $? == 0 ]; then
-   echo "LIST: <<$ops>>, Test has failed"
-   exit $SAME_ERROR
-fi
+echo "Cleaning tasks"
+echo "<br>"
 
-echo "OK, ACL entry has removed"
-echo "Clear VO, delete Role"
 voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeDefaultACL
@@ -15,8 +15,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -27,65 +25,70 @@ rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo ""
 date
-echo "VOMS-removeDefaultACL - started, VO=$vo_name, group=$GROUP, fake user=$USER"
+echo "<br>"
+echo "Test VOMS-removeDefaultACL:"
+echo "VO=$vo_name"
+echo "group=$GROUP"
+echo "fake user=$USER"
 
 
-echo "SCENARIO 1: empty VO"
-
+echo "SCENARIO: empty VO"
 voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Not defined ERROR: <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "SCENARIO 2: Create group <$GROUP> and add ACL entries"
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-
-echo "Again remove-acl-entry"
+echo "SCENARIO: Create group <$GROUP> and add ACL entries"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
 voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for group" $voms_stderr > /dev/null
 
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for group" $voms_stderr
 if [ $? == 1 ]; then
-   echo "Not correct diagnose: <<$voms_stderr>>, Test has filed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message"
+    echo "<br>"
+    cat $voms_stderr
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "OK, Create ACL entry for fake user in group $GROUP"
 voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $ALLOW $OP $USER
-
-echo "Again remove-acl-entry"
 voms-admin --vo=$vo_name -h $voms_host remove-default-acl-entry "/"$vo_name"/"$GROUP  $ALLOW $OP $USER
 
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-
-echo "Check result using get-acl"
-
 voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp
+grep "$user_subject" $voms_tmp > /dev/null
 
-grep "$user_subject" $voms_tmp
+ if [ $? == 0 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error removing the ACL"
+    echo "<br>"
+    cat $voms_tmp
+    echo "<br>"
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+ fi
 
-if [ $? == 0 ]; then
-   echo "LIST: <<$ops>>, Test has filed"
-   exit $SAME_ERROR
-fi
-echo "OK, ACL entry has removed"
-
-echo "Clear VO"
+echo "Cleaning tasks"
+echo "<br>"
+ 
 voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 rm -rf $tempo
 
-echo "Test is OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeMember b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeMember
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeMember
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-removeMember
@@ -14,8 +14,6 @@
 #                                                                                           #                                                               
 #############################################################################################
 #                                                                                           #
-# Note on security issues: the host and user certificates used by this test are dummy ones  #
-# provided by the test utils package.                                                       #
 #                                                                                           #
 #############################################################################################
 echo "<pre>"
@@ -24,101 +22,98 @@ source $SAME_SENSOR_HOME/tests/config_file
 
 rm -rf $voms_tmp
 rm -rf $voms_stderr
-#rm -rf $tempo
 
-echo ""
-date
-echo "VOMS-removeMember - started, VO=$vo_name, User=$USER, Group=$GROUP"
-
-echo "-------- Extract by openssl from usercert.pem ------"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 
-echo "DN=$user_subject"
-echo "SCENARIO 1: VO - empty"
+date
+echo "<br>"
+echo "test VOMS-RemoveMember:"
+echo "<br>"
+echo "VO=$vo_name"
+echo "<br>"
+echo "Group=$GROUP"
+echo "<br>"
+echo "User=$USER_subject"
+echo "<br>"
 
+echo "SCENARIO: VO empty"
+echo "<br>"
+echo "Remove non existing member from non existing group"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
-
-if [ $? == 1 ]; then
-   echo "Noncorrect diagnose <<"
-   cat $voms_stderr
-   echo ">>"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "Diag  - correct"
-fi
-
-echo "Create group $GROUP"
-
-voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP
-
-echo "Group has created, again remove member"
-voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
-
-
-grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Noncorrect diagnose <"
-   cat $voms_stderr
-   echo ">"
-   echo "Test has failed"
-   exit $SAME_ERROR
-else
-   echo "Diag  - correct"
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Create user"
+echo "SCENARIO: Create new group"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
+echo "Remove non existing member from group $GROUP"
+echo "<br>"
+voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
+grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null
 
+if [ $? == 1 ]; then
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Incorrect error message:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
+fi
+
+echo "SCENARIO: Create user"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-
-echo "User has created, add member to group"
-
+echo "Add member to group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER
-
-echo "Check members list"
 voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp
-#echo "Members list:"
-#cat $voms_tmp
-grep "$user_subject" $voms_tmp
+grep "$user_subject" $voms_tmp > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Member  not created, LIST:<<"
-   cat $voms_tmp
-   echo ">>, DN=$user_subject"
-   echo "Test has failed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error when adding member to group:"
+    echo "<br>"
+    cat $voms_tmp
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
-echo "Last remove member"
+echo "Remove member from group $GROUP"
+echo "<br>"
 voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
-
-echo "Check members list"
 voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
-#echo "Members list:"
-#cat $voms_tmp
-
-grep "No users are returned" $voms_stderr
+grep "No users are returned" $voms_stderr > /dev/null
 
 if [ $? == 1 ]; then
-   echo "Member  not removed, LIST:<<"
-   cat $voms_tmp
-   echo ">>, Test has failed"
-   exit $SAME_ERROR
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
+    echo "Error when deleting member from group:"
+    echo "<br>"
+    cat $voms_stderr
+    echo "Test has failed"
+    echo "<br>"
+    exit $SAME_ERROR
 fi
 
+echo "Cleaning tasks"
 
-echo "Test - Ok, leave empty VO"
-
-echo "Delete group"
-voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
-echo "Delete user"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-
+voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
 rm -rf $voms_tmp
 rm -rf $voms_stderr
 
-echo "Test - OK"
+echo "Test OK"
+echo "</pre>"
 exit $SAME_OK
