*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
@@ -33,10 +33,25 @@ echo "VOMS-PROXY-INIT: check option - $OPTION"
 echo "1. Create new user and proxy"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
 
+echo "Extract by openssl from usercert.pem"
+user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
+echo "DN=$user_subject"
+
 echo "1.1. Check 512 bits"
 voms-proxy-init -voms $vo_name  -$OPTION 512 -userconf $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 if [ $? = 1 ]; then
     echo "Test is failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "Execute voms-proxy-info"
+voms-proxy-info > $voms_tmp
+
+echo "2.3. Check user DN"
+grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
@@ -49,6 +64,18 @@ if [ $? = 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+echo "Execute voms-proxy-info"
+voms-proxy-info > $voms_tmp
+
+echo "2.3. Check user DN"
+grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+
 
 echo "1.3. Check 2048  bits"
 voms-proxy-init -voms $vo_name  -$OPTION 2048 -userconf $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
@@ -57,6 +84,18 @@ if [ $? = 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+echo "Execute voms-proxy-info"
+voms-proxy-info > $voms_tmp
+
+echo "Check user DN"
+grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+
 
 echo "1.4. Check 4096 bits"
 voms-proxy-init -voms $vo_name  -$OPTION 4096 -userconf $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
@@ -65,13 +104,7 @@ if [ $? = 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
-
-echo "2. Check proxy info"
-echo "2.1.Extract by openssl from usercert.pem"
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-echo "DN=$user_subject"
-
-echo "2.2. Execute voms-proxy-info"
+echo "Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
 
 echo "2.3. Check user DN"
@@ -85,8 +118,8 @@ fi
 
 echo "Test is OK"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-exit $SAME_OK
 
-echo "/pre"
+echo "</pre>"
+exit $SAME_OK
 
 
