*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-bits
@@ -45,9 +45,9 @@ if [ $? = 1 ]; then
     exit $SAME_ERROR
 fi
 echo "Execute voms-proxy-info"
-voms-proxy-info > $voms_tmp
+voms-proxy-info -all > $voms_tmp
 
-echo "2.3. Check user DN"
+echo "1.2. Check user DN"
 grep "$user_subject" $voms_tmp
 
 if [ $? == 1 ]; then
@@ -56,7 +56,18 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
-echo "1.2. Check 1024 bits"
+echo "1.3. Check strength"
+grep "strength  : 512 bits" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "OK"
+
+
+echo "2. Check 1024 bits"
 voms-proxy-init -voms $vo_name  -$OPTION 1024 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 
 if [ $? = 1 ]; then
@@ -67,7 +78,7 @@ fi
 echo "Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
 
-echo "2.3. Check user DN"
+echo "2.1. Check user DN"
 grep "$user_subject" $voms_tmp
 
 if [ $? == 1 ]; then
@@ -75,9 +86,17 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+echo "2.2. Check strength"
+grep "strength  : 1024 bits" $voms_tmp
 
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "OK"
 
-echo "1.3. Check 2048  bits"
+echo "3. Check 2048  bits"
 voms-proxy-init -voms $vo_name  -$OPTION 2048 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 if [ $? = 1 ]; then
     echo "Test is failed"
@@ -87,7 +106,7 @@ fi
 echo "Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
 
-echo "Check user DN"
+echo "3.1. Check user DN"
 grep "$user_subject" $voms_tmp
 
 if [ $? == 1 ]; then
@@ -96,8 +115,17 @@ if [ $? == 1 ]; then
     exit $SAME_ERROR
 fi
 
+echo "3.2. Check strength"
+grep "strength  : 2048 bits" $voms_tmp
 
-echo "1.4. Check 4096 bits"
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "OK"
+
+echo "4. Check 4096 bits"
 voms-proxy-init -voms $vo_name  -$OPTION 4096 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 if [ $? = 1 ]; then
    echo "Test is failed"
@@ -107,8 +135,16 @@ fi
 echo "Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
 
-echo "2.3. Check user DN"
+echo "4.1. Check user DN"
 grep "$user_subject" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "4.2. Check strength"
+grep "strength  : 4096 bits" $voms_tmp
 
 if [ $? == 1 ]; then
     echo "Test has failed"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-conf b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-conf
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-conf
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-conf
@@ -30,7 +30,8 @@ rm -rf $voms_tmp
 echo
 date
 echo "VOMS-PROXY-INIT: check option - $OPTION"
-
+echo "conf file $VOMS_CNF :"
+cat $VOMS_CNF
 
 echo "1. Create new user and proxy"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
@@ -52,8 +53,12 @@ echo "2.1.Extract by openssl from usercert.pem"
 user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
 echo "DN=$user_subject"
 
+sleep 5
+
 echo "2.2. Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
+cat $voms_tmp
+
 
 echo "2.3. Check user DN"
 grep "$user_subject" $voms_tmp
@@ -63,6 +68,45 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+
+echo "2.4. Check strength"
+grep "strength  : 512 bits" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+echo "OK"
+
+echo "2.5. Check vomslife"
+
+echo "Check timeleft"
+H1="12"
+H2=`grep "timeleft" $voms_tmp | cut -d":" -f2`
+
+echo "Compare $H1 (set time)  and $H2 (left time)"
+
+if [ ${H2} \< ${H1} ]; then
+   echo "OK"
+else
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+               
+echo "2.6. Check VO:"
+VO="VO        : $vo_name"
+voms-proxy-info -all > $voms_tmp
+
+grep "$VO" $voms_tmp
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi               
+               
+
 echo "Test is OK"
 voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-hours b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-hours
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-hours
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-hours
@@ -33,16 +33,21 @@ echo "VOMS-PROXY-INIT: check option - $OPTION"
 
 echo "1. Create new user and proxy"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-voms-proxy-init -voms $vo_name  -$OPTION "33" -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+
+H1="33"
+echo "set hours=$tim"
+voms-proxy-init -voms $vo_name  -$OPTION $H1 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 
 if [ $? = 0 ]; then
-   echo "Test is OK"
-   #exit $SAME_OK
+   echo "OK"
 else 
    echo "Test is failed"
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
 fi
+
+
+sleep 5
 
 echo "2. Check proxy info"
 echo "2.1.Extract by openssl from usercert.pem"
@@ -51,6 +56,8 @@ echo "DN=$user_subject"
 
 echo "2.2. Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
+cat $voms_tmp
+
 
 echo "2.3. Check user DN"
 grep "$user_subject" $voms_tmp
@@ -60,6 +67,23 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER    
     exit $SAME_ERROR
 fi
+
+
+echo "Check timeleft"
+H2=`grep "timeleft" $voms_tmp | cut -d":" -f2`
+
+
+echo "Compare $H1 and $H2"
+if [ ${H2} \< ${H1} ]; then
+   echo "OK"
+else
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+
+
+
     echo "Test is OK"
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-limit b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-limit
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-limit
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-limit
@@ -32,6 +32,7 @@ echo "VOMS-PROXY-INIT: check option - $OPTION"
 
 echo "1. Create new user and proxy"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
+#voms-proxy-destroy
 voms-proxy-init -voms $vo_name  -$OPTION -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 
 if [ $? = 0 ]; then
@@ -50,6 +51,7 @@ echo "DN=$user_subject"
 
 echo "2.2. Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
+cat $voms_tmp
 
 echo "2.3. Check user DN"
 grep "$user_subject" $voms_tmp
@@ -59,6 +61,15 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+echo "Check type of proxy"
+grep "limited" $voms_tmp
+
+if [ $? == 1 ]; then
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+
     echo "Test is OK"
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-valid b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-valid
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-valid
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-valid
@@ -37,8 +37,9 @@ echo "VOMS-PROXY-INIT: check option - $OPTION"
 echo "1. Create new user and proxy"
 echo "User=$USER"
 
+H1="11:00:00"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-voms-proxy-init -voms $vo_name  -$OPTION "33:33" -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+voms-proxy-init -voms $vo_name  -$OPTION $H1 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
 
 if [ $? = 0 ]; then
    echo "Test is OK"
@@ -56,6 +57,7 @@ echo "DN=$user_subject"
 
 echo "2.2. Execute voms-proxy-info"
 voms-proxy-info > $voms_tmp
+cat $voms_tmp
 
 echo "2.3. Check user DN"
 grep "$user_subject" $voms_tmp
@@ -65,6 +67,24 @@ if [ $? == 1 ]; then
     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
     exit $SAME_ERROR
 fi
+
+echo "Check timeleft"
+H1="11:00"
+H=`grep "timeleft" $voms_tmp | cut -d":" -f2`
+M=`grep "timeleft" $voms_tmp | cut -d":" -f3`
+H2="$H:$M"
+
+echo "Compare $H1(valid) and $H2 (left)"
+if [ ${H2} == ${H1} ]; then
+   echo "OK"
+else
+    echo "Test has failed"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    exit $SAME_ERROR
+fi
+               
+
+
         echo "Test is OK"
         voms-admin --vo=$vo_name -h $voms_host delete-user $USER
 echo "</pre>"
