*** empty log message ***

diff --git a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-list b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-list
--- a/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-list
+++ b/org.glite.testsuites.ctb/VOMS/tests/VOMS-pr-list
@@ -25,42 +25,95 @@ export voms_host=$1
 source $SAME_SENSOR_HOME/tests/pr_config_file
 export OPTION="list"
 rm -rf $voms_tmp
+group="test-group"
+groupi="/$vo_name/$group"
+role="User-group-role"
+
+function clearTask {
+    echo "Delete user, group"
+    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    echo "Delete role=$role"
+    voms-admin --vo=$vo_name -h $voms_host delete-role $role
+        
+    groupi="/$vo_name/$group"
+    echo "Delete group: $groupi"
+    voms-admin --vo=$vo_name -h $voms_host delete-group $groupi
+}
 
 echo
 date
 echo "VOMS-PROXY-INIT: check option - $OPTION"
 
-echo "1. Create new user and proxy"
+echo "1. Create new user"
 voms-admin --vo=$vo_name -h $voms_host create-user $USER
-voms-proxy-init -voms $vo_name  -$OPTION -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
+
+echo "1.2. Create group"
+
+echo "Create group: $groupi"
+    voms-admin --vo=$vo_name -h $voms_host create-group "$groupi"
+    
+    echo "1.3. Add user to group as group member"
+    
+    echo "Add member to group: $groupi"
+    voms-admin --vo=$vo_name -h $voms_host add-member $groupi $USER
+        
+    echo "1.3.1. List user groups:"
+    voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER
+    echo "Create role $role"
+    voms-admin --vo=$vo_name -h $voms_host create-role $role
+    echo "Assign user role in group"
+    voms-admin --vo=$vo_name -h $voms_host assign-role $groupi $role $USER
+    
+echo "Create proxy"
+voms-proxy-init -voms $vo_name  -$OPTION -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS 1> $voms_tmp
 
 if [ $? = 0 ]; then
-   echo "Test is OK"
+   echo "OK"
    #exit $SAME_OK
 else 
    echo "Test is failed"
-   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+   clearTASK
    exit $SAME_ERROR
 fi
+#echo "Result of voms-proxy-init:"
+#cat $voms_tmp
 
-echo "2. Check proxy info"
-echo "2.1.Extract by openssl from usercert.pem"
-user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
-echo "DN=$user_subject"
+patt1="/$vo_name/Role=NULL/Capability=NULL"
+patt2="$groupi/Role=$role/Capability=NULL"
+patt3="$groupi/Role=NULL/Capability=NULL"
 
-echo "2.2. Execute voms-proxy-info"
-voms-proxy-info > $voms_tmp
+echo "Patterns:"
+echo $patt1
+echo $patt2
+echo $patt3
 
-echo "2.3. Check user DN"
-grep "$user_subject" $voms_tmp
+echo "Check patterns:"
+grep "$patt1" $voms_tmp > /dev/null
 
-if [ $? == 1 ]; then
-    echo "Test has failed"
-     voms-admin --vo=$vo_name -h $voms_host delete-user $USER
-    exit $SAME_ERROR
+if [ $? = 1 ]; then
+   echo "Test is failed"
+   clearTask
+   exit $SAME_ERROR
+fi
+echo "OK"
+
+
+grep "$patt2" $voms_tmp > /dev/null
+if [ $? = 1 ]; then
+   echo "Test is failed"
+   clearTask
+   exit $SAME_ERROR
+fi
+echo "OK"
+
+grep "$patt3" $voms_tmp > /dev/null
+if [ $? = 1 ]; then
+   echo "Test is failed"
+   clearTask
+   exit $SAME_ERROR
 fi
     echo "Test is OK"
-    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
+    clearTask
 echo "</pre>"
 exit $SAME_OK
 
