*** empty log message ***

diff --git a/org.glite.testsuites.ctb/LFC/check-LFC b/org.glite.testsuites.ctb/LFC/check-LFC
--- a/org.glite.testsuites.ctb/LFC/check-LFC
+++ b/org.glite.testsuites.ctb/LFC/check-LFC
@@ -12,25 +12,25 @@ if [ "x$1" == "x--publish" ] ; then
 else
 #elif [ $nodeName = $realLFCserver ]; then   # my imsert (victor.galaktionov@cern.ch )
     echo "check-LFC - started"                # my insert
-    echo "$nodeName: started" >&2
+    #echo "$nodeName: started" >&2
     mkdir -p $SAME_SENSOR_WORK/nodes/$nodeName
     cd $SAME_SENSOR_WORK/nodes/$nodeName
     rm -f *.result
-    count=1
+    count=0
     for test in `cat $SAME_SENSOR_HOME/test-sequence.lst` ; do
-	echo
-	echo $count.
-	date
+	#echo
+	#echo $count.
+	#date
 	let count=count+1
-        echo "check-LFC: $test , nodename: $nodeName, VO: $SAME_VO"
+        echo "$count	check-LFC: $test,	nodename: $nodeName,	VO: $SAME_VO"
         same-run-test -v $SAME_VO -t $test -n $nodeName -e $envName -d $SAME_SENSOR_HOME/tests $nodeName > $test.result
         ret=$?
         #echo "Retcode=$ret"
-        if [ $ret == $SAME_OK ]; then
-           echo "Test is OK"
-        else
-           echo "Test is failed"
-        fi
+        #if [ $ret == $SAME_OK ]; then
+        #   echo "Test is OK"
+        #else
+        #   echo "Test is failed"
+        #fi
         #echo "<<<<<<<<<<<<<<<<<<<<<"
         #cat $test.result
         #echo ">>>>>>>>>>>>>>>>>>>>>"
