new version without SAM plus MyProxy removed

diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-basic b/org.glite.testsuites.ctb/FTS/tests/FTS-basic
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-basic
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-basic
@@ -1,125 +1,172 @@
-#!/bin/bash 
+#!/bin/bash
+
 ##########################################################################################
 # Script for testing of FTS services (Basic test: PING, FTS BDII, Top Level BDII, Tomcat)#
 ##########################################################################################
 #                                                       #
 # Returned values:                                      #
 #                                                       #
-#                 Exit  SAME_OK: Test Passed            #
-#                 Exit  SAME_ERROR: Test Failed         #
+#                 Exit  0: Test Passed                  #
+#                 Exit  1: Test Failed                  #
 #                 Exit  2: Wrong Input                  #
 #                                                       #
 #########################################################
 
 showUsage ()
 {
- echo "Missing parameter:                                                                 "
- echo "Usage:  FTS2-basic <fts hostname>                                                  "
- echo ""
+ echo "									 		  "
+ echo "Usage:  glite-fts-test-basic --fts <fts hostname> [ --bdii <bdii hostname> ]       "
+ echo "Options:                                                                           "
+ echo "	 obligatory:    								  "
+ echo "		  									  "
+ echo "	         --fts   <fts  hostname>						  "
+ echo "		         The name of the FTS server.					  "
+ echo "	 optional:									  "
+ echo "											  "	
+ echo "	         --bdii  <bdii hostname>  						  "
+ echo "		          The name of the top level BDII. The default is lcg-bdii.cern.ch "
+ echo "											  "
 }
 
-echo "<pre>"
 if [ -z "$1" ]; then
   showUsage
   exit 2
 fi
 
-if [ -n "$1" ]; then
- FTS_HOST=$1
-else
- echo "ERROR: No FTS host is defined!"
- echo "</pre>"
- exit $SAME_ERROR
+until [ -z "$1" ]
+do
+  case "$1" in
+   
+     --fts)
+           if [ -z "$2" ]; then
+                shift 1
+ 	   else
+                FTS_HOST=$2
+                shift 2
+           fi
+    ;;
+
+    --bdii)
+	   if [ -z "$2" ]; then
+               shift 1 
+ 	   else
+	       BDII_HOST=$2
+ 	       shift 2
+           fi
+    ;;
+
+    *)
+        showUsage
+        exit 2
+    ;;
+  esac	
+done
+
+if [ -z "$FTS_HOST" ]; then
+               echo ""
+               echo ">>> NOTE: FTS hostname is not specified. Option --fts <fts hostname> is obligatory! <<<"
+               showUsage
+               exit 2
 fi
 
-# Sourcing the configuration
+if [ -z "$BDII_HOST" ]; then
+              BDII_HOST=lcg-bdii.cern.ch
+fi
 
-. $SAME_SENSOR_HOME/config.sh
+######################################################################
+# >>>> NOTE:  Hardcoded ports for FTS BDII and top level BDII !!! <<<<
+######################################################################
+
+BDII_PORT=2170
+FTS_BDII_PORT=2170
 
 #####################
 # Exporting variables
 #####################
 
+export LCG_GFAL_INFOSYS=$BDII_HOST:$BDII_PORT
+export GLITE_SD_PLUGIN=bdii
 
+######################
+# Function definition
+######################
 
 function test_ping
 {
-  echo -n " Testing ping to $FTS_HOST" 
+  echo " Testing ping to $FTS_HOST" 
+  echo ""
   result=`ping -c 5 $FTS_HOST 2>/dev/null | grep Unreachable | wc -l`
 
   if [ $result -gt 0 ]; then
     echo ""
-    echo "<font color="red"> Error </font>: The $FTS_HOST is not accessible! "
+    echo ">>> NOTE: The $FTS_HOST is not accessible! <<<"
     echo ""
-    echo " <b> FTS Basic Test: </b>  <font color="red"> Failed. </font>"
-    echo "</pre>"
-    exit $SAME_ERROR
+    echo "FTS Basic Test: Failed."
+    echo ""
+    exit 1
   fi
-  echo "<font color="green"> - OK </font>"
 }
 
 function test_ldap
 {
-  echo ""
-  echo -n " Testing connection to LDAP server on $FTS_HOST"
+  echo " Testing connection to LDAP server on $FTS_HOST"
+  echo ""  
   result=`ldapsearch -x -H ldap://$FTS_HOST:$FTS_BDII_PORT -b Mds-vo-name=resource,o=Grid 2>/dev/null | tail -n 6 | grep Success | wc -l`
 
   if [ $result -eq 0 ]; then
      echo ""
-     echo "<font color="red"> Error: </font> LDAP Test: Failed. "
+     echo ">>> NOTE: LDAP Test: Failed. <<<"
      echo ""
-     echo " <b> FTS Basic Test: </b>  <font color="red"> Failed. </font>"
-     echo "</pre>"
-     exit $SAME_ERROR
+     echo "FTS Basic Test: Failed."
+     echo ""
+     exit 1	
   fi
-  echo "<font color="green"> - OK </font>"
 }
 
 function test_bdii
 {
+  echo " Testing if there is information for $FTS_HOST on $BDII_HOST"
   echo ""
-  echo -n " Testing if there is information for $FTS_HOST on $BDII_HOST"
 
   result=`ldapsearch -x -H ldap://$BDII_HOST:$BDII_PORT -b Mds-vo-name=local,o=Grid 2>/dev/null | grep $FTS_HOST | wc -l`
 
   if [ $result -eq 0 ]; then
     echo ""
-    echo "<font color="red">Error: </font> No entries found for FTS Server: $FTS_HOST on the top level BDII: $BDII_HOST! "
+    echo ">>> NOTE: No entries found for FTS Server: $FTS_HOST on the top level BDII: $BDII_HOST! <<<"
     echo ""
-    echo " <b> FTS Basic Test: </b>  <font color="red"> Failed. </font>"
-    echo "</pre>"
-    exit $SAME_ERROR
+    echo "FTS Basic Test: Failed."
+    echo ""
+    exit 1
   fi
-  echo "<font color="green"> - OK </font>"
 }
 
 function test_tomcat
 {
+  echo " Testing connection to Tomcat server on $FTS_HOST "
   echo ""
-  echo    " FTS's Tomcat is found to be running on port: $FTS_TOMCAT_PORT"
-  echo -n " Testing connection to Tomcat server on $FTS_HOST "
 
   result=`nmap -p $1 $FTS_HOST 2>/dev/null | grep open | wc -l`
 
   if [ $result -eq 0 ]; then
     echo ""
-    echo " <font color="red">   Error: </font> The Tomcat server on $FTS_HOST is not accessible! "
-    echo "  NOTE: Tomcat Test: Failed. Exiting."
-    echo " <b> FTS Basic Test: </b>  <font color="red"> Failed. </font>"
-    echo "</pre>"
-    exit $SAME_ERROR
+    echo ">>> NOTE: The Tomcat server on $FTS_HOST is not accessible! <<<"
+    echo ">>> NOTE: Tomcat Test: Failed. <<<"
+    echo ""
+    echo "FTS Basic Test: Failed."
+    echo ""
+    exit 1
   fi
-  echo "<font color="green"> - OK </font>"
 }
 
 ################
 # Start testing
 ###############
 
-export LCG_GFAL_INFOSYS=$BDII_HOST:$BDII_PORT
-export GLITE_SD_PLUGIN=bdii
-
-echo "Start testing with settings: FTS_HOST: $FTS_HOST BDII_HOST: $BDII_HOST"
+echo ""
+echo "Testing FTS: $FTS_HOST"
+echo ""
+echo "Using BDII: $BDII_HOST"
+echo ""
 echo "Testing...."
 echo ""
 
@@ -148,6 +195,7 @@ test_bdii
 FTS_URL=`glite-sd-query -t org.glite.FileTransfer 2>/dev/null | grep $FTS_HOST | grep Endpoint | sed -e 's/Endpoint://g'`
 FTS_URL=`echo $FTS_URL | awk '{print $1}' | sed -e 's/https:\/\///g' | sed 's/\// /g' | awk '{print $1}' | sed -e 's/:/ /g'`
 FTS_TOMCAT_PORT=`echo $FTS_URL | awk '{print $2}'`
+
 #######################################################
 # Checking if Tomcat Server on FTS is working properely
 #######################################################
@@ -155,6 +203,8 @@ FTS_TOMCAT_PORT=`echo $FTS_URL | awk '{print $2}'`
 test_tomcat $FTS_TOMCAT_PORT
 
 echo ""
-echo "<b> FTS Basic Test: </b> <font color="green"> Passed. </font>"
-echo "</pre>"
-exit $SAME_OK
+echo "FTS Basic Test: Passed."
+echo ""
+exit 0
+
+
diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-services b/org.glite.testsuites.ctb/FTS/tests/FTS-services
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-services
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-services
@@ -14,38 +14,95 @@
 
 showUsage ()
 {
- echo "Usage: FTS-services "
+ echo "                                                                                                       "
+ echo "Usage:   FTS-services --site <site name> [--bdii <bdii hostname>] "
+ echo "Options:                                                                                               "
+ echo "  obligatory:                                                                                          "
+ echo "                                                                                                       "
+ echo "          --site  <site name>                                                                          "
+ echo "                   The name of the site hosting the FTS server as it stored in the GOC DB and information system.             "
+ echo "                                                                                                       "
+ echo "  optional:                                                                                            "
+ echo "                                                                                                       "
+ echo "          --bdii  <bdii hostname>                                                                      "
+ echo "                   The name of the top level BDII. The default is lcg-bdii.cern.ch                     "
+ echo "													      "
 }
-echo "<pre>"
+
 if [ -z "$1" ]; then
   showUsage
   exit 2
 fi
 
-. $SAME_SENSOR_HOME/config.sh
-SITE_NAME=`cat $SAME_SENSOR_WORK/nodes/$1/siteName`
+until [ -z "$1" ] 
+do
+  case "$1" in
+
+     --site)
+           if [ -z "$2" ]; then
+		shift 1
+           else
+		SITE_NAME=$2
+                shift 2
+           fi
+     ;;
+
+     --bdii)
+           if [ -z "$2" ]; then
+                shift 1
+           else
+                BDII_HOST=$2
+                shift 2
+           fi
+     ;;
+
+
+          *)
+           showUsage
+           exit 2
+    ;;
+  esac
+done
+
+if [ -z "$SITE_NAME" ]; then
+   echo ""
+   echo ">>> NOTE: Site name is not specified. Option --site <site hostname> is obligatory! <<<"
+   showUsage
+   exit 2
+fi
+
+if [ -z "$BDII_HOST" ]; then
+   BDII_HOST=lcg-bdii.cern.ch
+fi
+
+
+######################################################################
+# >>>> NOTE:  Hardcoded port for top level BDII !!! <<<<
+######################################################################
+
+BDII_PORT=2170
 
 ################################
 # Checks if there is valid proxy
 ################################
+
 ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
 
 ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
 
 if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
          echo ""
-         echo " INFO: Using proxy from: $X509_USER_PROXY"
+         echo "Using proxy from: $X509_USER_PROXY"
 else
          echo ""
-         echo " <font color="red"> Error: </font> Valid proxy is needed for this test!"
+         echo ">>> NOTE: Valid proxy is needed for this test!"
          echo ""
          if [ $ProxyExpired -gt 0 ]; then
-            echo "<font color="red"> Error: </font> Proxy credential expired! Exiting."
+            echo ">>> NOTE: Proxy credential expired!"
          fi
          echo ""
-         exit $SAME_ERROR
+         exit 1
 fi
-
 
 #####################
 # Exporting variables
@@ -64,7 +121,18 @@ export GLITE_SD_PLUGIN=bdii
 
 unset $GLITE_SD_SITE
 
-FTS_HOST=$1
+FTS_URL=`glite-sd-query -s $SITE_NAME -t org.glite.FileTransfer 2>/dev/null | grep Endpoint | sed -e 's/Endpoint://g'`
+FTS_URL=`echo $FTS_URL | awk '{print $1}' | sed -e 's/https:\/\///g' | sed 's/\// /g' | awk '{print $1}' | sed -e 's/:/ /g'`
+FTS_HOST=`echo $FTS_URL | awk '{print $1}'`
+
+
+if [ -z "$FTS_HOST" ]; then
+   echo ""
+   echo ">>> NOTE: There is no information for FTS Server of the site: $SITE_NAME on  BDII: $BDII_HOST! <<< "
+   echo "" 
+   exit 1
+fi 
+
 
 export GLITE_SD_SITE=$SITE_NAME
 export LCG_CATALOG_TYPE='lfc'
@@ -112,13 +180,15 @@ if [ $result -eq 0 ]; then
 	done
 
 	echo ""
-	echo "FTS Test: <font color="green"> OK </font>"
+	echo "FTS Test: Passed."
 	echo ""
-        exit $SAME_OK
+        exit 0
 else
 	echo ">>> NOTE: `cat message`"
 	echo ""
-	echo "FTS Test: <font color="red"> Failed. </font>"
+	echo "FTS Test: Failed."
 	echo ""
-        exit $SAME_ERROR
+        exit 1
 fi
+
+
