*** empty log message ***

diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-common b/org.glite.testsuites.ctb/FTS/tests/FTS-common
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-common
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-common
@@ -378,24 +378,24 @@ function file_transfer_skip_tape()
 # If GSIFTP_URL is set to "yes", this will use GridFTP URLs
 function file_transfer_with_checksum()
 {
-    if [ -z $1 ];then
+   if [ -z $1 ];then
      echo "An SE source SRM location must be given to file_transfer_with_checksum()"
      return 2
-    else
+   else
      local SE1_SRM_LOC=$1
-    fi
+   fi
 
-    if [ -z $2 ];then
+   if [ -z $2 ];then
      echo "An SE destination SRM location must be given to file_transfer_with_checksum()"
      return 2
-    else
+   else
      local SE2_SRM_LOC=$2
-    fi
+   fi
 
-    if [ -z $3 ];then
+   if [ -z $3 ];then
      echo "A checksum algorithm must be given to file_transfer_with_checksum()"
      return 2
-    else
+   else
      local ALGO=$3
      if [ "x$ALGO" == "xSHA1" ]; then
        echo "WARNING: SHA1 will not be tested due to bug #..."
@@ -403,19 +403,35 @@ function file_transfer_with_checksum()
      fi
    fi
 
-   if [ -z $4 ];then
-     echo "No --compare-checksum option will be used"
-     OPTION=""
-   else
-     echo "Using --compare-option" 
-     OPTION=$4
-   fi
+  # Shift three times and process optional
+  shift 3
 
-   if [ -z $5 ];then
-     echo "" >> /dev/null #do nothing
-   else
-     echo "Using 3rd scenarios with both --compare-checksum and algorithm"
-   fi
+  AWK_PARAMETER='{print $1}'
+
+  until [ -z "$1" ]
+  do
+    case "$1" in
+      --compare-checksum)
+        echo "Using --compare-option" 
+        OPTION=$1
+      ;;
+      both)
+        echo "Using 3rd scenarios with both --compare-checksum and algorithm"
+        BOTH="yes"
+      ;;
+      --lowercase)
+        AWK_PARAMETER='{print tolower($1)}'
+      ;;
+      --uppercase)
+        AWK_PARAMETER='{print toupper($1)}'
+      ;;
+      *)
+        echo "Wrong parameter $1"
+        return 1
+    esac
+    shift 1
+  done
+
 
     SUB_FILE_LOC="$HOME/fts-submission-file"
     RESULT_FILE="$HOME/fts-test-results"
@@ -451,23 +467,23 @@ function file_transfer_with_checksum()
 
     if [ "x$OPTION" == "x" ]; then
       echo "Retrieving the checksum for $SURL"
-      CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk '{print $1}'`
+      CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk $AWK_PARAMETER
       echo "Creating the submission file with $ALGO:$CHECKSUM in $SUB_FILE_LOC"
       i=0
       echo "" > $SUB_FILE_LOC
 
-    # Process the destination and source URLs depending on
-    # the GSIFTP_URL environment variable
-    if [ "x$GSIFTP_URL" = "xyes" ]; then
-        get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
-        if [ ! $? -eq 0 ]; then
-            echo "get_gsiftp_urls error!"
-            return 1
-        fi
-        echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
-    else
-        echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
-    fi
+      # Process the destination and source URLs depending on
+      # the GSIFTP_URL environment variable
+      if [ "x$GSIFTP_URL" = "xyes" ]; then
+          get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
+          if [ ! $? -eq 0 ]; then
+              echo "get_gsiftp_urls error!"
+              return 1
+          fi
+          echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
+      else
+          echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
+      fi
 
       echo "Submitting the transfer"  
       echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer -f $SUB_FILE_LOC" 
@@ -476,23 +492,23 @@ function file_transfer_with_checksum()
          echo "Job submition failed!"
          return 1
       fi
-    elif [ "x$5" == "x" ]; then
+    elif [ "x$BOTH" == "x" ]; then
       echo "Creating the submission file in $SUB_FILE_LOC"
       i=0
       echo "" > $SUB_FILE_LOC
 
-    # Process the destination and source URLs depending on
-    # the GSIFTP_URL environment variable
-    if [ "x$GSIFTP_URL" = "xyes" ]; then
-        get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
-        if [ ! $? -eq 0 ]; then
-            echo "get_gsiftp_urls error!"
-            return 1
-        fi
-        echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION" >> $SUB_FILE_LOC
-    else
-        echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i" >> $SUB_FILE_LOC
-    fi
+      # Process the destination and source URLs depending on
+      # the GSIFTP_URL environment variable
+      if [ "x$GSIFTP_URL" = "xyes" ]; then
+          get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
+          if [ ! $? -eq 0 ]; then
+              echo "get_gsiftp_urls error!"
+              return 1
+          fi
+          echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION" >> $SUB_FILE_LOC
+      else
+          echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i" >> $SUB_FILE_LOC
+      fi
       
       echo "Submitting the transfer with $OPTION"  
       echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC" 
@@ -503,24 +519,24 @@ function file_transfer_with_checksum()
       fi
     else
       echo "Retrieving the checksum for $SURL"
-      CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk '{print $1}'`
+      CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk $AWK_PARAMETER
       echo "Creating the submission file with $ALGO:$CHECKSUM in $SUB_FILE_LOC"
       i=0
       echo "" > $SUB_FILE_LOC
 
 
-    # Process the destination and source URLs depending on
-    # the GSIFTP_URL environment variable
-    if [ "x$GSIFTP_URL" = "xyes" ]; then
-        get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
-        if [ ! $? -eq 0 ]; then
-            echo "get_gsiftp_urls error!"
-            return 1
-        fi
-        echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
-    else
-        echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
-    fi
+      # Process the destination and source URLs depending on
+      # the GSIFTP_URL environment variable
+      if [ "x$GSIFTP_URL" = "xyes" ]; then
+          get_gsiftp_urls "$SE1_SRM_LOC/$TEST_FILE_NAME" "$SE2_SRM_LOC/$TEST_FILE_NAME$i"
+          if [ ! $? -eq 0 ]; then
+              echo "get_gsiftp_urls error!"
+              return 1
+          fi
+          echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
+      else
+          echo "$SE1_SRM_LOC/$TEST_FILE_NAME $SE2_SRM_LOC/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
+      fi
 
       echo "Submitting the transfer with $OPTION"  
       echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC" 
