Adapted to execute tests in the FTS node

diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-add b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-add
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-add
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-add
@@ -35,12 +35,6 @@ showUsage()
  echo "                   The name of the FTS host."
  echo "          --channel  <channel name> "
  echo "                   The channel to use for submitting a file transfer"
- echo "          --bdii  <bdii hostname> "
- echo "                   The top-level BDII hostname"
- echo "          --vo  <VO name> "
- echo "                   VO name"
- echo "          --timeout  <timeout> "
- echo "                   timeout in seconds"
 }
 
 # FTS_HOST must be set.
@@ -148,7 +142,7 @@ function channel-add()
     return 0
 }
 
-if [ $# -ne 10 ];then
+if [ $# -ne 4 ];then
   showUsage
   echo
   echo "-TEST FAILED-"
@@ -174,53 +168,31 @@ do
                 shift 2
            fi
      ;;
-     --bdii)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                BDII_HOST=$2
-                shift 2
-           fi
-     ;;
-     --vo)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                VO_NAME=$2
-                shift 2
-           fi
-     ;;
-     --timeout)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                TIMEOUT=$2
-                shift 2
-           fi
-     ;;
           *)
            showUsage
            exit 2
     ;;
   esac
 done
-
+echo $FTS_HOST
 #0.1) Check for valid proxy
-ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
-ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
+if [ $FTS_HOST != "localhost" ]; then
+  ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
+  ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
 
-if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
-         echo ""
-         echo "Using proxy from: $X509_USER_PROXY"
-else
-         echo ""
-         echo ">>> NOTE: Valid proxy is needed for this test!"
-         echo ""
-         if [ $ProxyExpired -gt 0 ]; then
-            echo ">>> NOTE: Proxy credential expired!"
-         fi
-         echo "-TEST FAILED-"
-         exit 1
+  if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
+           echo ""
+           echo "Using proxy from: $X509_USER_PROXY"
+  else
+           echo ""
+           echo ">>> NOTE: Valid proxy is needed for this test!"
+           echo ""
+           if [ $ProxyExpired -gt 0 ]; then
+              echo ">>> NOTE: Proxy credential expired!"
+           fi
+           echo "-TEST FAILED-"
+           exit 1
+  fi
 fi
 
 echo "1) Test if channel exists"
diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-signal b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-signal
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-signal
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-signal
@@ -151,21 +151,23 @@ fi
 BDII_PORT=2170
 
 #0.1) Check for valid proxy
-ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
-ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
+if [ $FTS_HOST != "localhost" ]; then
+  ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
+  ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
 
-if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
-         echo ""
-         echo "Using proxy from: $X509_USER_PROXY"
-else
-         echo ""
-         echo ">>> NOTE: Valid proxy is needed for this test!"
-         echo ""
-         if [ $ProxyExpired -gt 0 ]; then
-            echo ">>> NOTE: Proxy credential expired!"
-         fi
-         echo "-TEST FAILED-"
-         exit 1
+  if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
+           echo ""
+           echo "Using proxy from: $X509_USER_PROXY"
+  else
+           echo ""
+           echo ">>> NOTE: Valid proxy is needed for this test!"
+           echo ""
+           if [ $ProxyExpired -gt 0 ]; then
+              echo ">>> NOTE: Proxy credential expired!"
+           fi
+           echo "-TEST FAILED-"
+           exit 1
+  fi
 fi
 
 #1) Test if channel exists
diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-vomanagers b/org.glite.testsuites.ctb/FTS/tests/FTS-vomanagers
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-vomanagers
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-vomanagers
@@ -180,7 +180,7 @@ function special-check-vomanagers()
 }
 
 
-if [ $# -ne 10 ];then
+if [ $# -ne 4 ];then
   showUsage
   echo
   echo "-TEST FAILED-"
@@ -206,30 +206,6 @@ do
                 shift 2
            fi
      ;;
-     --bdii)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                BDII_HOST=$2
-                shift 2
-           fi
-     ;;
-     --vo)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                VO_NAME=$2
-                shift 2
-           fi
-     ;;
-     --timeout)
-           if [ -z "$2" ]; then
-                shift 1
-           else
-                TIMEOUT=$2
-                shift 2
-           fi
-     ;;
           *)
            showUsage
            exit 2
@@ -239,21 +215,23 @@ done
 
 
 #0.1) Check for valid proxy
-ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
-ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
+if [ $FTS_HOST != "localhost" ]; then
+  ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
+  ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`
 
-if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
-         echo ""
-         echo "Using proxy from: $X509_USER_PROXY"
-else
-         echo ""
-         echo ">>> NOTE: Valid proxy is needed for this test!"
-         echo ""
-         if [ $ProxyExpired -gt 0 ]; then
-            echo ">>> NOTE: Proxy credential expired!"
-         fi
-         echo "-TEST FAILED-"
-         exit 1
+  if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
+           echo ""
+           echo "Using proxy from: $X509_USER_PROXY"
+  else
+           echo ""
+           echo ">>> NOTE: Valid proxy is needed for this test!"
+           echo ""
+           if [ $ProxyExpired -gt 0 ]; then
+              echo ">>> NOTE: Proxy credential expired!"
+           fi
+           echo "-TEST FAILED-"
+           exit 1
+  fi
 fi
 
 echo "Set user DN"
