removed hardcoded SEs

diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-joblist b/org.glite.testsuites.ctb/FTS/tests/FTS-joblist
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-joblist
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-joblist
@@ -457,36 +457,34 @@ echo "Source: $Source_Site"
 echo "Dest: $Destin_Site"
 
 #3.b) Retrieve good SEs from source and destination sites
-#get_def_se_from_site $Source_Site
-#if [ $? -eq 1 ];then
-#  echo "Failing retrieving good SE from site $Source_Site"
-#  exit 1
-#fi
-#if [ "x$SE_HOST" != "x" ]; then
-#  SE_SOURCE=$SE_HOST
-#  echo "SE_source: $SE_SOURCE"
-#else
-#  echo "Failing retrieving good SE from site $Source_Site"
-#  echo "-TEST FAILED-"
-#  exit 1
-#fi
+get_def_se_from_site $Source_Site
+if [ $? -eq 1 ];then
+  echo "Failing retrieving good SE from site $Source_Site"
+  exit 1
+fi
+if [ "x$SE_HOST" != "x" ]; then
+  SE_SOURCE=$SE_HOST
+  echo "SE_source: $SE_SOURCE"
+else
+  echo "Failing retrieving good SE from site $Source_Site"
+  echo "-TEST FAILED-"
+  exit 1
+fi
 
 #get_def_se_from_site $Destin_Site
-#if [ $? -eq 1 ];then
-#  echo "Failing retrieving default SE from site $Destin_Site"
-#  echo "-TEST FAILED-"
-#  exit 1
-#fi
-#if [ "x$SE_HOST" != "x" ]; then
-#  SE_DEST=$SE_HOST
-#  echo "SE_dest: $SE_DEST"
-#else
-#  echo "Failing retrieving default SE from site $Source_Site"
-#  echo "-TEST FAILED-"
-#  exit 1
-#fi
-SE_SOURCE=$CERN_SE
-SE_DEST=$CERN_SE2
+if [ $? -eq 1 ];then
+  echo "Failing retrieving default SE from site $Destin_Site"
+  echo "-TEST FAILED-"
+  exit 1
+fi
+if [ "x$SE_HOST" != "x" ]; then
+  SE_DEST=$SE_HOST
+  echo "SE_dest: $SE_DEST"
+else
+  echo "Failing retrieving default SE from site $Source_Site"
+  echo "-TEST FAILED-"
+  exit 1
+fi
 
 
 #3.c) Retrieve SEs path to use for file transfer
