*** empty log message ***

diff --git a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-set b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-set
--- a/org.glite.testsuites.ctb/FTS/tests/FTS-channel-set
+++ b/org.glite.testsuites.ctb/FTS/tests/FTS-channel-set
@@ -26,7 +26,7 @@
 
 showUsage()
 {
- echo "Usage: FTS-channel-add --fts <fts hostname> --channel <channel name>"
+ echo "Usage: FTS-channel-set --fts <fts hostname> --channel <channel name>"
  echo "Options: "
  echo "          --fts  <fts hostname> "
  echo "                   The name of the FTS host."
@@ -125,30 +125,36 @@ is-channel-exists $CHANNEL
 
 if [ $? != 0 ]; then
     echo "Channel is not exists, create it"
-    #CHANNEL="CERN-JINR"
-    BANDWIDTH=100
-    CONTACT="vgalakti@cern.ch"
-    STATE="Stopped"
-    STREAMS=5
-    FILES=10
-    THROUGHPUT=7
     SITE_A="CERN-TB-CERN"
     SITE_B="SINPCERTTB"
 
     echo "Add new channel"
-    channel-add $CHANNEL $BANDWIDTH $CONTACT $STATE $STREAMS $FILES $THROUGHPUT $SITE_A $SITE_B
+    simple-channel-add $CHANNEL $SITE_A $SITE_B
     if [ $? != 0 ]; then
 	echo "Add channel - failed"
 	exit 1
     fi        
 fi
 
+BANDWIDTH=100
+CONTACT="vgalakti@cern.ch"
+STATE="Stopped"
+STREAMS=5
+FILES=10
+THROUGHPUT=7
+MESSAGE="My test message"
+echo "Check parameters BANDWIDTH CONTACT STATE STREAMS THROUGHPUT FILES MESSAGE"
+channel-set $CHANNEL $BANDWIDTH $CONTACT $STATE $STREAMS $THROUGHPUT $FILES "$MESSAGE"   
+if [ $? != 0 ]; then
+    echo "Set channel - failed"
+    exit 1
+fi               
 
 echo "Check special parameters for add channel command"
-special-check-channel-add $CHANNEL $SITE_A $SITE_B
+special-channel-set $CHANNEL
 
 if [ $? != 0 ]; then
-    echo "Add channel - failed"
+    echo "Set channel - failed"
     exit 1
 fi     
 
